-- SINNER development database bootstrap: Phases 1 and 2
-- GENERATED FILE. Do not edit this file directly.
-- Regenerate with: node supabase/sql-editor/build-bundle.mjs
-- Intended for a fresh Supabase development project. Run exactly once.
-- The transaction guarantees an all-or-nothing installation.
--
-- Source manifest:
-- supabase/migrations/20260907130000_core_foundation.sql | sha256:ad64c469e88cd6cabe892d759c67e768f20ce1cc6b9945d9df32a82d7a1c252c
-- supabase/migrations/20260907170000_spaces_marketplace.sql | sha256:ed45038a2d5f1adfb1c50e5b39d3885abf235bb81312a474bc599f5b862da360
-- supabase/migrations/20260907210000_mexico_nationwide_locations.sql | sha256:fd1e9cc857b6eab211920acc6211e315ce9be0055fb789df24f6c0cd35b03435
-- supabase/seed.sql | sha256:aae430c0cbeaac66f6e72cffe2a0e00c0434de0b55d30e9bca21b6a309fc3d63
-- supabase/sql-editor/verify_phase_1_2.sql | sha256:764ab96ecdac97c20c532a9109ed906e23238e94077439a01a7b7d2063464488

begin;

-- ============================================================================
-- 1. SOURCE: supabase/migrations/20260907130000_core_foundation.sql
-- ============================================================================

create extension if not exists pgcrypto;

create type public.user_role as enum ('guest', 'host', 'admin');
create type public.verification_status as enum ('unverified', 'pending', 'verified', 'rejected');
create type public.space_status as enum ('draft', 'pending_review', 'approved', 'rejected', 'suspended');
create type public.availability_status as enum ('available', 'blocked', 'reserved');
create type public.booking_status as enum ('draft', 'pending', 'approved', 'payment_pending', 'confirmed', 'completed', 'cancelled', 'declined', 'refunded', 'disputed');
create type public.listing_status as enum ('draft', 'pending_review', 'approved', 'rejected', 'suspended');
create type public.event_visibility as enum ('public', 'private', 'invite_only');
create type public.ticket_status as enum ('valid', 'used', 'cancelled', 'refunded');
create type public.report_status as enum ('open', 'reviewing', 'resolved', 'dismissed');

create schema if not exists private;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null check (char_length(first_name) between 1 and 80),
  last_name text not null check (char_length(last_name) between 1 and 80),
  display_name text check (display_name is null or char_length(display_name) <= 80),
  avatar_url text,
  bio text check (bio is null or char_length(bio) <= 500),
  date_of_birth date not null check (date_of_birth <= current_date - interval '18 years'),
  identity_verification_status public.verification_status not null default 'unverified',
  age_verification_status public.verification_status not null default 'unverified',
  terms_accepted_at timestamptz not null,
  privacy_accepted_at timestamptz not null,
  adult_confirmation_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.user_role not null default 'guest',
  created_at timestamptz not null default now(),
  unique (user_id, role)
);
create index user_roles_user_id_idx on public.user_roles(user_id);

create table public.spaces (
  id uuid primary key default gen_random_uuid(),
  host_id uuid references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 140),
  slug text not null unique,
  description text,
  space_type text not null,
  status public.space_status not null default 'draft',
  city text not null,
  state text not null,
  country text not null default 'Mexico',
  latitude numeric(10,7),
  longitude numeric(10,7),
  approximate_location text,
  exact_address text,
  max_guests integer not null default 2 check (max_guests > 0),
  hourly_price numeric(12,2) check (hourly_price is null or hourly_price >= 0),
  overnight_price numeric(12,2) check (overnight_price is null or overnight_price >= 0),
  full_day_price numeric(12,2) check (full_day_price is null or full_day_price >= 0),
  cleaning_fee numeric(12,2) not null default 0 check (cleaning_fee >= 0),
  minimum_hours integer not null default 1 check (minimum_hours > 0),
  privacy_score numeric(3,1) check (privacy_score between 0 and 10),
  instant_booking boolean not null default false,
  creator_friendly boolean not null default false,
  group_friendly boolean not null default false,
  events_allowed boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index spaces_host_id_idx on public.spaces(host_id);
create index spaces_status_published_idx on public.spaces(status, published_at desc);
create index spaces_city_idx on public.spaces(city);

create table public.space_photos (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  storage_path text not null,
  sort_order integer not null default 0,
  is_cover boolean not null default false,
  created_at timestamptz not null default now(),
  unique (space_id, storage_path)
);
create index space_photos_space_id_idx on public.space_photos(space_id, sort_order);

create table public.amenities (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  category text not null
);

create table public.space_amenities (
  space_id uuid not null references public.spaces(id) on delete cascade,
  amenity_id uuid not null references public.amenities(id) on delete cascade,
  primary key (space_id, amenity_id)
);
create index space_amenities_amenity_id_idx on public.space_amenities(amenity_id);

create table public.allowed_uses (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique
);

create table public.space_allowed_uses (
  space_id uuid not null references public.spaces(id) on delete cascade,
  allowed_use_id uuid not null references public.allowed_uses(id) on delete cascade,
  allowed boolean not null default false,
  details text,
  primary key (space_id, allowed_use_id)
);
create index space_allowed_uses_allowed_use_id_idx on public.space_allowed_uses(allowed_use_id);

create table public.availability (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  date date not null,
  start_time time not null,
  end_time time not null,
  status public.availability_status not null default 'available',
  created_at timestamptz not null default now(),
  check (start_time <> end_time),
  unique (space_id, date, start_time, end_time)
);
create index availability_space_date_idx on public.availability(space_id, date, start_time);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  guest_id uuid not null references auth.users(id) on delete restrict,
  space_id uuid not null references public.spaces(id) on delete restrict,
  start_datetime timestamptz not null,
  end_datetime timestamptz not null,
  guest_count integer not null check (guest_count > 0),
  status public.booking_status not null default 'draft',
  base_amount numeric(12,2) not null default 0 check (base_amount >= 0),
  cleaning_fee numeric(12,2) not null default 0 check (cleaning_fee >= 0),
  service_fee numeric(12,2) not null default 0 check (service_fee >= 0),
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  currency char(3) not null default 'MXN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_datetime > start_datetime)
);
create index bookings_guest_id_idx on public.bookings(guest_id, start_datetime desc);
create index bookings_space_id_idx on public.bookings(space_id, start_datetime desc);

create table public.favorites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  space_id uuid not null references public.spaces(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, space_id)
);
create index favorites_space_id_idx on public.favorites(space_id);

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings(id) on delete restrict,
  author_id uuid not null references auth.users(id) on delete restrict,
  space_id uuid not null references public.spaces(id) on delete cascade,
  overall_rating smallint not null check (overall_rating between 1 and 5),
  cleanliness_rating smallint check (cleanliness_rating between 1 and 5),
  privacy_rating smallint check (privacy_rating between 1 and 5),
  accuracy_rating smallint check (accuracy_rating between 1 and 5),
  host_rating smallint check (host_rating between 1 and 5),
  discretion_rating smallint check (discretion_rating between 1 and 5),
  comment text check (comment is null or char_length(comment) <= 3000),
  created_at timestamptz not null default now(),
  unique (booking_id, author_id)
);
create index reviews_space_id_idx on public.reviews(space_id, created_at desc);
create index reviews_author_id_idx on public.reviews(author_id);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  space_id uuid references public.spaces(id) on delete set null,
  booking_id uuid references public.bookings(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.conversation_participants (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);
create index conversation_participants_user_id_idx on public.conversation_participants(user_id);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete restrict,
  body text not null check (char_length(body) between 1 and 5000),
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index messages_conversation_created_idx on public.messages(conversation_id, created_at);
create index messages_sender_id_idx on public.messages(sender_id);

create table public.experiences (
  id uuid primary key default gen_random_uuid(),
  host_id uuid references auth.users(id) on delete cascade,
  name text not null,
  slug text not null unique,
  description text,
  city text not null,
  state text not null,
  country text not null default 'Mexico',
  duration_minutes integer check (duration_minutes is null or duration_minutes > 0),
  max_guests integer not null default 2 check (max_guests > 0),
  price numeric(12,2) check (price is null or price >= 0),
  currency char(3) not null default 'MXN',
  status public.listing_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index experiences_host_id_idx on public.experiences(host_id);
create index experiences_status_idx on public.experiences(status);

create table public.events (
  id uuid primary key default gen_random_uuid(),
  organizer_id uuid references auth.users(id) on delete cascade,
  name text not null,
  slug text not null unique,
  description text,
  city text not null,
  state text not null,
  country text not null default 'Mexico',
  venue_name text,
  event_date date not null,
  start_time time not null,
  end_time time not null,
  capacity integer not null check (capacity > 0),
  ticket_price numeric(12,2) check (ticket_price is null or ticket_price >= 0),
  currency char(3) not null default 'MXN',
  visibility public.event_visibility not null default 'public',
  status public.listing_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (start_time <> end_time)
);
create index events_organizer_id_idx on public.events(organizer_id);
create index events_status_date_idx on public.events(status, event_date);

create table public.event_tickets (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status public.ticket_status not null default 'valid',
  ticket_code text not null unique default encode(gen_random_bytes(12), 'hex'),
  created_at timestamptz not null default now(),
  unique (event_id, user_id)
);
create index event_tickets_user_id_idx on public.event_tickets(user_id);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('booking_requested','booking_approved','booking_declined','booking_cancelled','booking_confirmed','new_message','new_review','event_reminder','listing_approved','listing_rejected','verification_required')),
  title text not null,
  body text not null,
  read_at timestamptz,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index notifications_user_unread_idx on public.notifications(user_id, read_at, created_at desc);

create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references auth.users(id) on delete restrict,
  target_type text not null check (target_type in ('profile','space','experience','event','message','review')),
  target_id uuid not null,
  reason text not null,
  description text,
  status public.report_status not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index reports_reporter_id_idx on public.reports(reporter_id);
create index reports_status_idx on public.reports(status, created_at);

create function private.is_admin()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists (select 1 from public.user_roles where user_id = (select auth.uid()) and role = 'admin') $$;

create function private.is_host()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists (select 1 from public.user_roles where user_id = (select auth.uid()) and role = 'host') $$;

create function private.owns_space(space_uuid uuid)
returns boolean language sql stable security definer set search_path = ''
as $$ select exists (select 1 from public.spaces where id = space_uuid and host_id = (select auth.uid())) $$;

create function private.owns_event(event_uuid uuid)
returns boolean language sql stable security definer set search_path = ''
as $$ select exists (select 1 from public.events where id = event_uuid and organizer_id = (select auth.uid())) $$;

create function private.is_conversation_participant(conversation_uuid uuid)
returns boolean language sql stable security definer set search_path = ''
as $$ select exists (select 1 from public.conversation_participants where conversation_id = conversation_uuid and user_id = (select auth.uid())) $$;

revoke all on schema private from public;
grant usage on schema private to anon, authenticated;
grant execute on function private.is_admin() to anon, authenticated;
grant execute on function private.is_host() to authenticated;
grant execute on function private.owns_space(uuid) to authenticated;
grant execute on function private.owns_event(uuid) to authenticated;
grant execute on function private.is_conversation_participant(uuid) to authenticated;

create function public.request_host_role()
returns void language plpgsql security definer set search_path = ''
as $$
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  insert into public.user_roles(user_id, role) values ((select auth.uid()), 'host') on conflict do nothing;
end;
$$;
revoke all on function public.request_host_role() from public;
grant execute on function public.request_host_role() to authenticated;

create function private.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;

create trigger profiles_updated_at before update on public.profiles for each row execute function private.set_updated_at();
create trigger spaces_updated_at before update on public.spaces for each row execute function private.set_updated_at();
create trigger bookings_updated_at before update on public.bookings for each row execute function private.set_updated_at();
create trigger conversations_updated_at before update on public.conversations for each row execute function private.set_updated_at();
create trigger experiences_updated_at before update on public.experiences for each row execute function private.set_updated_at();
create trigger events_updated_at before update on public.events for each row execute function private.set_updated_at();
create trigger reports_updated_at before update on public.reports for each row execute function private.set_updated_at();

create function private.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (
    id, first_name, last_name, display_name, date_of_birth,
    terms_accepted_at, privacy_accepted_at, adult_confirmation_at
  ) values (
    new.id,
    trim(new.raw_user_meta_data ->> 'first_name'),
    trim(new.raw_user_meta_data ->> 'last_name'),
    nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
    (new.raw_user_meta_data ->> 'date_of_birth')::date,
    (new.raw_user_meta_data ->> 'terms_accepted_at')::timestamptz,
    (new.raw_user_meta_data ->> 'privacy_accepted_at')::timestamptz,
    (new.raw_user_meta_data ->> 'adult_confirmation_at')::timestamptz
  );
  insert into public.user_roles(user_id, role) values (new.id, 'guest');
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();

create view public.public_profiles with (security_barrier = true) as
select id, display_name, avatar_url, bio, created_at from public.profiles;

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.spaces enable row level security;
alter table public.space_photos enable row level security;
alter table public.amenities enable row level security;
alter table public.space_amenities enable row level security;
alter table public.allowed_uses enable row level security;
alter table public.space_allowed_uses enable row level security;
alter table public.availability enable row level security;
alter table public.bookings enable row level security;
alter table public.favorites enable row level security;
alter table public.reviews enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages enable row level security;
alter table public.experiences enable row level security;
alter table public.events enable row level security;
alter table public.event_tickets enable row level security;
alter table public.notifications enable row level security;
alter table public.reports enable row level security;

revoke all on all tables in schema public from anon, authenticated;
grant select on public.public_profiles, public.amenities, public.allowed_uses to anon, authenticated;
grant select (id, host_id, name, slug, description, space_type, status, city, state, country, latitude, longitude, approximate_location, max_guests, hourly_price, overnight_price, full_day_price, cleaning_fee, minimum_hours, privacy_score, instant_booking, creator_friendly, group_friendly, events_allowed, published_at, created_at, updated_at) on public.spaces to anon, authenticated;
grant select on public.space_photos, public.space_amenities, public.space_allowed_uses, public.availability, public.reviews, public.experiences, public.events to anon, authenticated;
grant select, insert, update, delete on public.profiles, public.user_roles, public.space_photos, public.space_amenities, public.space_allowed_uses, public.availability, public.bookings, public.favorites, public.reviews, public.conversations, public.conversation_participants, public.messages, public.experiences, public.events, public.event_tickets, public.notifications, public.reports to authenticated;
grant insert, update, delete on public.spaces to authenticated;

create policy "profiles_select_own" on public.profiles for select to authenticated using ((select auth.uid()) = id or private.is_admin());
create policy "profiles_update_own" on public.profiles for update to authenticated using ((select auth.uid()) = id or private.is_admin()) with check ((select auth.uid()) = id or private.is_admin());

create policy "roles_select_own" on public.user_roles for select to authenticated using ((select auth.uid()) = user_id or private.is_admin());
create policy "roles_admin_insert" on public.user_roles for insert to authenticated with check (private.is_admin());
create policy "roles_admin_update" on public.user_roles for update to authenticated using (private.is_admin()) with check (private.is_admin());
create policy "roles_admin_delete" on public.user_roles for delete to authenticated using (private.is_admin());

create policy "spaces_public_or_owner_select" on public.spaces for select to anon, authenticated using (status = 'approved' or host_id = (select auth.uid()) or private.is_admin());
create policy "spaces_host_insert" on public.spaces for insert to authenticated with check (host_id = (select auth.uid()) and private.is_host());
create policy "spaces_host_update" on public.spaces for update to authenticated using (host_id = (select auth.uid()) or private.is_admin()) with check (host_id = (select auth.uid()) or private.is_admin());
create policy "spaces_host_delete" on public.spaces for delete to authenticated using ((host_id = (select auth.uid()) and status = 'draft') or private.is_admin());

create policy "space_photos_visible_space" on public.space_photos for select to anon, authenticated using (exists (select 1 from public.spaces s where s.id = space_id and (s.status = 'approved' or s.host_id = (select auth.uid()) or private.is_admin())));
create policy "space_photos_owner_insert" on public.space_photos for insert to authenticated with check (private.owns_space(space_id) or private.is_admin());
create policy "space_photos_owner_update" on public.space_photos for update to authenticated using (private.owns_space(space_id) or private.is_admin()) with check (private.owns_space(space_id) or private.is_admin());
create policy "space_photos_owner_delete" on public.space_photos for delete to authenticated using (private.owns_space(space_id) or private.is_admin());

create policy "amenities_public_select" on public.amenities for select to anon, authenticated using (true);
create policy "allowed_uses_public_select" on public.allowed_uses for select to anon, authenticated using (true);

create policy "space_amenities_visible" on public.space_amenities for select to anon, authenticated using (exists (select 1 from public.spaces s where s.id = space_id and (s.status = 'approved' or s.host_id = (select auth.uid()) or private.is_admin())));
create policy "space_amenities_owner_insert" on public.space_amenities for insert to authenticated with check (private.owns_space(space_id) or private.is_admin());
create policy "space_amenities_owner_delete" on public.space_amenities for delete to authenticated using (private.owns_space(space_id) or private.is_admin());

create policy "space_uses_visible" on public.space_allowed_uses for select to anon, authenticated using (exists (select 1 from public.spaces s where s.id = space_id and (s.status = 'approved' or s.host_id = (select auth.uid()) or private.is_admin())));
create policy "space_uses_owner_insert" on public.space_allowed_uses for insert to authenticated with check (private.owns_space(space_id) or private.is_admin());
create policy "space_uses_owner_update" on public.space_allowed_uses for update to authenticated using (private.owns_space(space_id) or private.is_admin()) with check (private.owns_space(space_id) or private.is_admin());
create policy "space_uses_owner_delete" on public.space_allowed_uses for delete to authenticated using (private.owns_space(space_id) or private.is_admin());

create policy "availability_visible" on public.availability for select to anon, authenticated using (exists (select 1 from public.spaces s where s.id = space_id and (s.status = 'approved' or s.host_id = (select auth.uid()) or private.is_admin())));
create policy "availability_owner_insert" on public.availability for insert to authenticated with check (private.owns_space(space_id) or private.is_admin());
create policy "availability_owner_update" on public.availability for update to authenticated using (private.owns_space(space_id) or private.is_admin()) with check (private.owns_space(space_id) or private.is_admin());
create policy "availability_owner_delete" on public.availability for delete to authenticated using (private.owns_space(space_id) or private.is_admin());

create policy "bookings_parties_select" on public.bookings for select to authenticated using (guest_id = (select auth.uid()) or private.owns_space(space_id) or private.is_admin());
create policy "bookings_guest_insert" on public.bookings for insert to authenticated with check (guest_id = (select auth.uid()) and exists (select 1 from public.spaces s where s.id = space_id and s.status = 'approved'));
create policy "bookings_parties_update" on public.bookings for update to authenticated using (guest_id = (select auth.uid()) or private.owns_space(space_id) or private.is_admin()) with check (guest_id = (select auth.uid()) or private.owns_space(space_id) or private.is_admin());

create policy "favorites_own_select" on public.favorites for select to authenticated using (user_id = (select auth.uid()));
create policy "favorites_own_insert" on public.favorites for insert to authenticated with check (user_id = (select auth.uid()));
create policy "favorites_own_delete" on public.favorites for delete to authenticated using (user_id = (select auth.uid()));

create policy "reviews_public_select" on public.reviews for select to anon, authenticated using (true);
create policy "reviews_completed_booking_insert" on public.reviews for insert to authenticated with check (author_id = (select auth.uid()) and exists (select 1 from public.bookings b where b.id = booking_id and b.guest_id = (select auth.uid()) and b.space_id = space_id and b.status = 'completed'));
create policy "reviews_author_delete" on public.reviews for delete to authenticated using (author_id = (select auth.uid()) or private.is_admin());

create policy "conversations_participant_select" on public.conversations for select to authenticated using (private.is_conversation_participant(id) or private.is_admin());
create policy "conversation_participants_member_select" on public.conversation_participants for select to authenticated using (private.is_conversation_participant(conversation_id) or private.is_admin());
create policy "messages_participant_select" on public.messages for select to authenticated using (private.is_conversation_participant(conversation_id) or private.is_admin());
create policy "messages_participant_insert" on public.messages for insert to authenticated with check (sender_id = (select auth.uid()) and private.is_conversation_participant(conversation_id));
create policy "messages_sender_update" on public.messages for update to authenticated using (sender_id = (select auth.uid())) with check (sender_id = (select auth.uid()));

create policy "experiences_public_or_owner_select" on public.experiences for select to anon, authenticated using (status = 'approved' or host_id = (select auth.uid()) or private.is_admin());
create policy "experiences_host_insert" on public.experiences for insert to authenticated with check (host_id = (select auth.uid()) and private.is_host());
create policy "experiences_host_update" on public.experiences for update to authenticated using (host_id = (select auth.uid()) or private.is_admin()) with check (host_id = (select auth.uid()) or private.is_admin());
create policy "experiences_host_delete" on public.experiences for delete to authenticated using ((host_id = (select auth.uid()) and status = 'draft') or private.is_admin());

create policy "events_public_or_owner_select" on public.events for select to anon, authenticated using (status = 'approved' or organizer_id = (select auth.uid()) or private.is_admin());
create policy "events_host_insert" on public.events for insert to authenticated with check (organizer_id = (select auth.uid()) and private.is_host());
create policy "events_host_update" on public.events for update to authenticated using (organizer_id = (select auth.uid()) or private.is_admin()) with check (organizer_id = (select auth.uid()) or private.is_admin());
create policy "events_host_delete" on public.events for delete to authenticated using ((organizer_id = (select auth.uid()) and status = 'draft') or private.is_admin());

create policy "tickets_owner_or_organizer_select" on public.event_tickets for select to authenticated using (user_id = (select auth.uid()) or private.owns_event(event_id) or private.is_admin());
create policy "tickets_owner_insert" on public.event_tickets for insert to authenticated with check (user_id = (select auth.uid()) and exists (select 1 from public.events e where e.id = event_id and e.status = 'approved'));
create policy "tickets_organizer_update" on public.event_tickets for update to authenticated using (private.owns_event(event_id) or private.is_admin()) with check (private.owns_event(event_id) or private.is_admin());

create policy "notifications_own_select" on public.notifications for select to authenticated using (user_id = (select auth.uid()));
create policy "notifications_own_update" on public.notifications for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "notifications_own_delete" on public.notifications for delete to authenticated using (user_id = (select auth.uid()));

create policy "reports_own_select" on public.reports for select to authenticated using (reporter_id = (select auth.uid()) or private.is_admin());
create policy "reports_own_insert" on public.reports for insert to authenticated with check (reporter_id = (select auth.uid()));
create policy "reports_admin_update" on public.reports for update to authenticated using (private.is_admin()) with check (private.is_admin());

-- ============================================================================
-- 2. SOURCE: supabase/migrations/20260907170000_spaces_marketplace.sql
-- ============================================================================

-- Phase 2: public Spaces marketplace, privacy-safe reads and hourly availability.

alter table public.spaces add column if not exists short_description text;
alter table public.spaces add column if not exists featured boolean not null default false;
alter table public.spaces add column if not exists cancellation_policy text;
alter table public.spaces add column if not exists check_in_notes text;
alter table public.spaces add column if not exists minimum_booking_notice_minutes integer not null default 120;
alter table public.spaces add column if not exists buffer_minutes integer not null default 30;
alter table public.spaces add column if not exists rating_average numeric(3,2) not null default 0;
alter table public.spaces add column if not exists review_count integer not null default 0;
alter table public.spaces add column if not exists house_rules jsonb not null default '[]'::jsonb;
alter table public.space_photos add column if not exists alt_text text;
alter table public.amenities add column if not exists icon_name text;

create index if not exists spaces_marketplace_order_idx
  on public.spaces(status, featured desc, rating_average desc, privacy_score desc, published_at desc);
create index if not exists spaces_capacity_idx on public.spaces(status, max_guests);
create index if not exists spaces_hourly_price_idx on public.spaces(status, hourly_price);

update public.spaces
set short_description = left(coalesce(description, name), 180)
where short_description is null;

update public.spaces
set house_rules = jsonb_build_array(
  jsonb_build_object('key', 'guests', 'label', 'Maximum guests', 'detail', 'Up to ' || max_guests || ' registered guests'),
  jsonb_build_object('key', 'smoking', 'label', 'Smoking', 'detail', 'Confirm the host policy before booking'),
  jsonb_build_object('key', 'noise', 'label', 'Noise', 'detail', 'Keep sound within the private space'),
  jsonb_build_object('key', 'cleaning', 'label', 'Cleaning', 'detail', 'Leave the space in the condition described by the host')
)
where house_rules = '[]'::jsonb;

update public.amenities
set name = 'Jacuzzi', slug = 'jacuzzi', icon_name = 'bath'
where slug = 'private-jacuzzi'
  and not exists (select 1 from public.amenities existing where existing.slug = 'jacuzzi');

insert into public.amenities(name, slug, category, icon_name) values
  ('Jacuzzi', 'jacuzzi', 'wellness', 'bath'),
  ('Pool', 'pool', 'wellness', 'waves'),
  ('Private entrance', 'private-entrance', 'privacy', 'door-open'),
  ('Private parking', 'private-parking', 'access', 'car'),
  ('Self check-in', 'self-check-in', 'privacy', 'key-round'),
  ('Soundproofing', 'soundproofing', 'privacy', 'volume-x'),
  ('Wi-Fi', 'wifi', 'comfort', 'wifi'),
  ('Air conditioning', 'air-conditioning', 'comfort', 'snowflake'),
  ('Shower', 'shower', 'wellness', 'shower-head'),
  ('Bathtub', 'bathtub', 'wellness', 'bath'),
  ('Mirrors', 'mirrors', 'studio', 'scan'),
  ('Lighting equipment', 'lighting-equipment', 'studio', 'lamp-desk'),
  ('Tripod', 'tripod', 'studio', 'camera'),
  ('Kitchen', 'kitchen', 'comfort', 'cooking-pot'),
  ('Terrace', 'terrace', 'outdoor', 'sunset'),
  ('Outdoor area', 'outdoor-area', 'outdoor', 'trees')
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  icon_name = excluded.icon_name;

create or replace function private.refresh_space_rating()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_space_id uuid;
begin
  if tg_op = 'DELETE' then
    target_space_id := old.space_id;
  else
    target_space_id := new.space_id;
  end if;

  update public.spaces s
  set rating_average = coalesce(summary.average_rating, 0),
      review_count = coalesce(summary.total_reviews, 0),
      updated_at = now()
  from (
    select round(avg(r.overall_rating)::numeric, 2) as average_rating,
           count(*)::integer as total_reviews
    from public.reviews r
    where r.space_id = target_space_id
  ) summary
  where s.id = target_space_id;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists refresh_space_rating_after_review on public.reviews;
create trigger refresh_space_rating_after_review
after insert or update or delete on public.reviews
for each row execute function private.refresh_space_rating();

update public.spaces s
set rating_average = coalesce(summary.average_rating, 0),
    review_count = coalesce(summary.total_reviews, 0)
from (
  select space_id, round(avg(overall_rating)::numeric, 2) as average_rating, count(*)::integer as total_reviews
  from public.reviews
  group by space_id
) summary
where s.id = summary.space_id;

create or replace view public.public_host_profiles
with (security_barrier = true)
as
select
  p.id,
  coalesce(nullif(p.display_name, ''), p.first_name) as display_name,
  p.avatar_url,
  p.bio,
  (p.identity_verification_status = 'verified' and p.age_verification_status = 'verified') as is_verified,
  p.created_at,
  round(avg(r.overall_rating)::numeric, 2) as host_rating
from public.profiles p
join public.user_roles ur on ur.user_id = p.id and ur.role = 'host'
left join public.spaces s on s.host_id = p.id and s.status = 'approved'
left join public.reviews r on r.space_id = s.id
group by p.id, p.display_name, p.first_name, p.avatar_url, p.bio, p.identity_verification_status, p.age_verification_status, p.created_at;

create or replace view public.public_space_reviews
with (security_barrier = true)
as
select
  r.id,
  r.space_id,
  r.overall_rating,
  r.comment,
  r.created_at,
  coalesce(nullif(p.display_name, ''), 'Verified guest') as author_display_name,
  p.avatar_url as author_avatar_url
from public.reviews r
join public.spaces s on s.id = r.space_id and s.status = 'approved'
left join public.profiles p on p.id = r.author_id;

revoke all on public.public_host_profiles, public.public_space_reviews from public;
grant select on public.public_host_profiles, public.public_space_reviews to anon, authenticated;

-- Public and ordinary authenticated clients can only project privacy-safe columns.
revoke select on public.spaces from anon, authenticated;
revoke select (exact_address, latitude, longitude) on public.spaces from anon, authenticated;
grant select (
  id, host_id, name, slug, short_description, description, space_type, status,
  city, state, country, approximate_location, max_guests,
  hourly_price, overnight_price, full_day_price, cleaning_fee, minimum_hours,
  privacy_score, instant_booking, creator_friendly, group_friendly, events_allowed,
  featured, cancellation_policy, check_in_notes, minimum_booking_notice_minutes,
  buffer_minutes, rating_average, review_count, house_rules,
  published_at, created_at, updated_at
) on public.spaces to anon, authenticated;

-- Booking and account identifiers are not part of public review responses.
revoke select on public.reviews from anon, authenticated;
grant select (id, space_id, overall_rating, cleanliness_rating, privacy_rating, accuracy_rating, host_rating, discretion_rating, comment, created_at)
  on public.reviews to anon, authenticated;
drop policy if exists "reviews_public_select" on public.reviews;
drop policy if exists "reviews_visible_space" on public.reviews;
create policy "reviews_visible_space" on public.reviews
for select to anon, authenticated
using (
  exists (select 1 from public.spaces s where s.id = space_id and s.status = 'approved')
  or author_id = (select auth.uid())
  or private.owns_space(space_id)
  or private.is_admin()
);

-- Raw availability intervals are host data. Public users receive only a yes/no RPC result.
drop policy if exists "availability_visible" on public.availability;
drop policy if exists "availability_owner_select" on public.availability;
create policy "availability_owner_select" on public.availability
for select to authenticated
using (private.owns_space(space_id) or private.is_admin());
revoke select on public.availability from anon, authenticated;
grant select on public.availability to authenticated;

create or replace function public.check_space_availability(
  p_space_id uuid,
  p_date date,
  p_start time,
  p_duration_hours integer,
  p_guests integer default 1
)
returns boolean
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  requested_start timestamptz;
  requested_end timestamptz;
  space_capacity integer;
  minimum_duration integer;
  notice_minutes integer;
  turnover_minutes integer;
begin
  if p_date is null or p_start is null or p_duration_hours is null or p_duration_hours <= 0 or p_duration_hours > 24 or p_guests <= 0 then
    return false;
  end if;

  select max_guests, minimum_hours, minimum_booking_notice_minutes, buffer_minutes
  into space_capacity, minimum_duration, notice_minutes, turnover_minutes
  from public.spaces
  where id = p_space_id and status = 'approved';

  if not found or p_guests > space_capacity or p_duration_hours < minimum_duration then
    return false;
  end if;

  requested_start := (p_date + p_start) at time zone 'America/Mexico_City';
  requested_end := requested_start + make_interval(hours => p_duration_hours);

  if requested_start < now() + make_interval(mins => notice_minutes) then
    return false;
  end if;

  return not exists (
    select 1
    from public.availability a
    where a.space_id = p_space_id
      and a.status in ('blocked', 'reserved')
      and requested_start < (
        (a.date + a.end_time + case when a.end_time <= a.start_time then interval '1 day' else interval '0 days' end)
        at time zone 'America/Mexico_City'
      ) + make_interval(mins => turnover_minutes)
      and requested_end > ((a.date + a.start_time) at time zone 'America/Mexico_City') - make_interval(mins => turnover_minutes)
  ) and not exists (
    select 1
    from public.bookings b
    where b.space_id = p_space_id
      and b.status in ('pending', 'approved', 'payment_pending', 'confirmed')
      and requested_start < b.end_datetime + make_interval(mins => turnover_minutes)
      and requested_end > b.start_datetime - make_interval(mins => turnover_minutes)
  );
end;
$$;

revoke all on function public.check_space_availability(uuid, date, time, integer, integer) from public;
grant execute on function public.check_space_availability(uuid, date, time, integer, integer) to anon, authenticated;

create or replace function public.search_public_spaces(
  p_location text default null,
  p_date date default null,
  p_start time default null,
  p_duration_hours integer default 4,
  p_guests integer default 1,
  p_min_price numeric default null,
  p_max_price numeric default null,
  p_privacy numeric default null,
  p_space_type text default null,
  p_amenity_slugs text[] default '{}'::text[],
  p_allowed_use_slugs text[] default '{}'::text[],
  p_creator_friendly boolean default false,
  p_group_friendly boolean default false,
  p_events_allowed boolean default false,
  p_instant_booking boolean default false,
  p_sort text default 'recommended',
  p_page integer default 1,
  p_page_size integer default 6
)
returns table (
  id uuid,
  slug text,
  name text,
  short_description text,
  space_type text,
  city text,
  state text,
  country text,
  approximate_location text,
  max_guests integer,
  hourly_price numeric,
  overnight_price numeric,
  full_day_price numeric,
  cleaning_fee numeric,
  minimum_hours integer,
  privacy_score numeric,
  instant_booking boolean,
  creator_friendly boolean,
  group_friendly boolean,
  events_allowed boolean,
  featured boolean,
  published_at timestamptz,
  rating_average numeric,
  review_count integer,
  cover_photo text,
  amenity_slugs text[],
  amenity_names text[],
  amenity_categories text[],
  amenity_icons text[],
  allowed_use_slugs text[],
  allowed_use_names text[],
  total_count bigint
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with candidates as (
    select
      s.*,
      coalesce(s.hourly_price, s.overnight_price, s.full_day_price) as starting_price,
      (select sp.storage_path from public.space_photos sp where sp.space_id = s.id order by sp.is_cover desc, sp.sort_order asc limit 1) as cover_photo,
      array(select a.slug from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id where sa.space_id = s.id order by a.slug) as amenity_slugs,
      array(select a.name from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id where sa.space_id = s.id order by a.slug) as amenity_names,
      array(select a.category from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id where sa.space_id = s.id order by a.slug) as amenity_categories,
      array(select coalesce(a.icon_name, '') from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id where sa.space_id = s.id order by a.slug) as amenity_icons,
      array(select u.slug from public.space_allowed_uses su join public.allowed_uses u on u.id = su.allowed_use_id where su.space_id = s.id and su.allowed order by u.slug) as allowed_use_slugs,
      array(select u.name from public.space_allowed_uses su join public.allowed_uses u on u.id = su.allowed_use_id where su.space_id = s.id and su.allowed order by u.slug) as allowed_use_names
    from public.spaces s
    where s.status = 'approved'
      and s.max_guests >= greatest(coalesce(p_guests, 1), 1)
      and (nullif(trim(p_location), '') is null or lower(concat_ws(' ', s.city, s.state, s.country, s.approximate_location)) like '%' || lower(trim(p_location)) || '%')
      and (p_min_price is null or coalesce(s.hourly_price, s.overnight_price, s.full_day_price) >= p_min_price)
      and (p_max_price is null or coalesce(s.hourly_price, s.overnight_price, s.full_day_price) <= p_max_price)
      and (p_privacy is null or s.privacy_score >= p_privacy)
      and (nullif(p_space_type, '') is null or case when replace(lower(s.space_type), ' ', '-') in ('private-suite','apartment','villa','studio','playroom','venue') then replace(lower(s.space_type), ' ', '-') else 'other' end = p_space_type)
      and (not p_creator_friendly or s.creator_friendly)
      and (not p_group_friendly or s.group_friendly)
      and (not p_events_allowed or s.events_allowed)
      and (not p_instant_booking or s.instant_booking)
      and not exists (
        select 1 from unnest(coalesce(p_amenity_slugs, '{}'::text[])) requested(slug)
        where not exists (
          select 1 from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id
          where sa.space_id = s.id and a.slug = requested.slug
        )
      )
      and not exists (
        select 1 from unnest(coalesce(p_allowed_use_slugs, '{}'::text[])) requested(slug)
        where not exists (
          select 1 from public.space_allowed_uses su join public.allowed_uses u on u.id = su.allowed_use_id
          where su.space_id = s.id and su.allowed and u.slug = requested.slug
        )
      )
      and (p_date is null or p_start is null or public.check_space_availability(s.id, p_date, p_start, p_duration_hours, p_guests))
  )
  select
    c.id, c.slug, c.name, c.short_description, c.space_type, c.city, c.state, c.country,
    c.approximate_location, c.max_guests, c.hourly_price, c.overnight_price, c.full_day_price,
    c.cleaning_fee, c.minimum_hours, c.privacy_score, c.instant_booking, c.creator_friendly,
    c.group_friendly, c.events_allowed, c.featured, c.published_at, c.rating_average, c.review_count,
    c.cover_photo, c.amenity_slugs, c.amenity_names, c.amenity_categories, c.amenity_icons,
    c.allowed_use_slugs, c.allowed_use_names, count(*) over () as total_count
  from candidates c
  order by
    case when p_sort = 'recommended' then c.featured::integer end desc nulls last,
    case when p_sort in ('recommended', 'rating') then c.rating_average end desc nulls last,
    case when p_sort = 'recommended' then c.privacy_score end desc nulls last,
    case when p_sort = 'privacy' then c.privacy_score end desc nulls last,
    case when p_sort = 'price-asc' then c.starting_price end asc nulls last,
    case when p_sort = 'price-desc' then c.starting_price end desc nulls last,
    case when p_sort = 'newest' then c.published_at end desc nulls last,
    c.published_at desc nulls last,
    c.slug asc
  limit least(greatest(coalesce(p_page_size, 6), 1), 24)
  offset (greatest(coalesce(p_page, 1), 1) - 1) * least(greatest(coalesce(p_page_size, 6), 1), 24);
$$;

comment on function public.search_public_spaces is
  'Recommended order is deterministic: featured, rating average, Privacy Score, publication date, then slug.';

revoke all on function public.search_public_spaces(text, date, time, integer, integer, numeric, numeric, numeric, text, text[], text[], boolean, boolean, boolean, boolean, text, integer, integer) from public;
grant execute on function public.search_public_spaces(text, date, time, integer, integer, numeric, numeric, numeric, text, text[], text[], boolean, boolean, boolean, boolean, text, integer, integer) to anon, authenticated;

comment on column public.spaces.exact_address is
  'Private. Never grant this column to anon/authenticated clients; expose only through a future confirmed-booking authorization function.';

-- ============================================================================
-- 3. SOURCE: supabase/migrations/20260907210000_mexico_nationwide_locations.sql
-- ============================================================================

-- Nationwide Mexico location support for the Spaces marketplace.

create extension if not exists pg_trgm with schema extensions;

alter table public.spaces add column if not exists country_code text not null default 'MX';
alter table public.spaces add column if not exists state_code text;
alter table public.spaces add column if not exists municipality text;
alter table public.spaces add column if not exists locality text;
alter table public.spaces add column if not exists postal_code text;
alter table public.spaces add column if not exists location_search_text text not null default '';

alter table public.spaces drop constraint if exists spaces_country_code_format;
alter table public.spaces add constraint spaces_country_code_format
  check (country_code ~ '^[A-Z]{2}$');
alter table public.spaces drop constraint if exists spaces_state_code_format;
alter table public.spaces add constraint spaces_state_code_format
  check (state_code is null or state_code ~ '^[A-Z]{3}$');
alter table public.spaces drop constraint if exists spaces_postal_code_format;
alter table public.spaces add constraint spaces_postal_code_format
  check (postal_code is null or postal_code ~ '^[0-9]{5}$');

create or replace function private.normalize_mexico_location(value text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select trim(
    regexp_replace(
      translate(lower(coalesce(value, '')), 'áéíóúüñàèìòù', 'aeiouunaeiou'),
      '[^a-z0-9]+',
      ' ',
      'g'
    )
  )
$$;

revoke all on function private.normalize_mexico_location(text) from public;

create or replace function private.set_space_location_search()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.location_search_text := private.normalize_mexico_location(
    coalesce(new.locality, '') || ' ' ||
    coalesce(new.city, '') || ' ' ||
    coalesce(new.municipality, '') || ' ' ||
    coalesce(new.state, '') || ' ' ||
    coalesce(new.state_code, '') || ' ' ||
    coalesce(new.country, '') || ' ' ||
    coalesce(new.country_code, '') || ' ' ||
    coalesce(new.approximate_location, '')
  );
  return new;
end;
$$;

drop trigger if exists spaces_location_search_before_write on public.spaces;
create trigger spaces_location_search_before_write
before insert or update of locality, city, municipality, state, state_code, country,
  country_code, approximate_location
on public.spaces
for each row execute function private.set_space_location_search();

update public.spaces
set location_search_text = private.normalize_mexico_location(
  coalesce(locality, '') || ' ' ||
  coalesce(city, '') || ' ' ||
  coalesce(municipality, '') || ' ' ||
  coalesce(state, '') || ' ' ||
  coalesce(state_code, '') || ' ' ||
  coalesce(country, '') || ' ' ||
  coalesce(country_code, '') || ' ' ||
  coalesce(approximate_location, '')
);

create index if not exists spaces_location_search_trgm_idx
  on public.spaces using gin (location_search_text extensions.gin_trgm_ops)
  where status = 'approved';

grant select (country_code, state_code, municipality, locality)
  on public.spaces to anon, authenticated;
revoke select (postal_code, location_search_text, exact_address, latitude, longitude)
  on public.spaces from anon, authenticated;

create or replace function public.search_public_spaces(
  p_location text default null,
  p_date date default null,
  p_start time default null,
  p_duration_hours integer default 4,
  p_guests integer default 1,
  p_min_price numeric default null,
  p_max_price numeric default null,
  p_privacy numeric default null,
  p_space_type text default null,
  p_amenity_slugs text[] default '{}'::text[],
  p_allowed_use_slugs text[] default '{}'::text[],
  p_creator_friendly boolean default false,
  p_group_friendly boolean default false,
  p_events_allowed boolean default false,
  p_instant_booking boolean default false,
  p_sort text default 'recommended',
  p_page integer default 1,
  p_page_size integer default 6
)
returns table (
  id uuid,
  slug text,
  name text,
  short_description text,
  space_type text,
  city text,
  state text,
  country text,
  approximate_location text,
  max_guests integer,
  hourly_price numeric,
  overnight_price numeric,
  full_day_price numeric,
  cleaning_fee numeric,
  minimum_hours integer,
  privacy_score numeric,
  instant_booking boolean,
  creator_friendly boolean,
  group_friendly boolean,
  events_allowed boolean,
  featured boolean,
  published_at timestamptz,
  rating_average numeric,
  review_count integer,
  cover_photo text,
  amenity_slugs text[],
  amenity_names text[],
  amenity_categories text[],
  amenity_icons text[],
  allowed_use_slugs text[],
  allowed_use_names text[],
  total_count bigint
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with candidates as (
    select
      s.*,
      coalesce(s.hourly_price, s.overnight_price, s.full_day_price) as starting_price,
      (select sp.storage_path from public.space_photos sp where sp.space_id = s.id order by sp.is_cover desc, sp.sort_order asc limit 1) as cover_photo,
      array(select a.slug from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id where sa.space_id = s.id order by a.slug) as amenity_slugs,
      array(select a.name from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id where sa.space_id = s.id order by a.slug) as amenity_names,
      array(select a.category from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id where sa.space_id = s.id order by a.slug) as amenity_categories,
      array(select coalesce(a.icon_name, '') from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id where sa.space_id = s.id order by a.slug) as amenity_icons,
      array(select u.slug from public.space_allowed_uses su join public.allowed_uses u on u.id = su.allowed_use_id where su.space_id = s.id and su.allowed order by u.slug) as allowed_use_slugs,
      array(select u.name from public.space_allowed_uses su join public.allowed_uses u on u.id = su.allowed_use_id where su.space_id = s.id and su.allowed order by u.slug) as allowed_use_names
    from public.spaces s
    where s.status = 'approved'
      and s.max_guests >= greatest(coalesce(p_guests, 1), 1)
      and (
        nullif(private.normalize_mexico_location(p_location), '') is null
        or s.location_search_text like '%' || private.normalize_mexico_location(p_location) || '%'
      )
      and (p_min_price is null or coalesce(s.hourly_price, s.overnight_price, s.full_day_price) >= p_min_price)
      and (p_max_price is null or coalesce(s.hourly_price, s.overnight_price, s.full_day_price) <= p_max_price)
      and (p_privacy is null or s.privacy_score >= p_privacy)
      and (nullif(p_space_type, '') is null or case when replace(lower(s.space_type), ' ', '-') in ('private-suite','apartment','villa','studio','playroom','venue') then replace(lower(s.space_type), ' ', '-') else 'other' end = p_space_type)
      and (not p_creator_friendly or s.creator_friendly)
      and (not p_group_friendly or s.group_friendly)
      and (not p_events_allowed or s.events_allowed)
      and (not p_instant_booking or s.instant_booking)
      and not exists (
        select 1 from unnest(coalesce(p_amenity_slugs, '{}'::text[])) requested(slug)
        where not exists (
          select 1 from public.space_amenities sa join public.amenities a on a.id = sa.amenity_id
          where sa.space_id = s.id and a.slug = requested.slug
        )
      )
      and not exists (
        select 1 from unnest(coalesce(p_allowed_use_slugs, '{}'::text[])) requested(slug)
        where not exists (
          select 1 from public.space_allowed_uses su join public.allowed_uses u on u.id = su.allowed_use_id
          where su.space_id = s.id and su.allowed and u.slug = requested.slug
        )
      )
      and (p_date is null or p_start is null or public.check_space_availability(s.id, p_date, p_start, p_duration_hours, p_guests))
  )
  select
    c.id, c.slug, c.name, c.short_description, c.space_type, c.city, c.state, c.country,
    c.approximate_location, c.max_guests, c.hourly_price, c.overnight_price, c.full_day_price,
    c.cleaning_fee, c.minimum_hours, c.privacy_score, c.instant_booking, c.creator_friendly,
    c.group_friendly, c.events_allowed, c.featured, c.published_at, c.rating_average, c.review_count,
    c.cover_photo, c.amenity_slugs, c.amenity_names, c.amenity_categories, c.amenity_icons,
    c.allowed_use_slugs, c.allowed_use_names, count(*) over () as total_count
  from candidates c
  order by
    case when p_sort = 'recommended' then c.featured::integer end desc nulls last,
    case when p_sort in ('recommended', 'rating') then c.rating_average end desc nulls last,
    case when p_sort = 'recommended' then c.privacy_score end desc nulls last,
    case when p_sort = 'privacy' then c.privacy_score end desc nulls last,
    case when p_sort = 'price-asc' then c.starting_price end asc nulls last,
    case when p_sort = 'price-desc' then c.starting_price end desc nulls last,
    case when p_sort = 'newest' then c.published_at end desc nulls last,
    c.published_at desc nulls last,
    c.slug asc
  limit least(greatest(coalesce(p_page_size, 6), 1), 24)
  offset (greatest(coalesce(p_page, 1), 1) - 1) * least(greatest(coalesce(p_page_size, 6), 1), 24);
$$;

create or replace function public.search_mexico_locations(
  p_query text default '',
  p_limit integer default 8
)
returns table (
  label text,
  locality text,
  city text,
  municipality text,
  state text,
  state_code text,
  country_code text
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with locations as (
    select distinct
      s.locality,
      s.city,
      s.municipality,
      s.state,
      s.state_code,
      s.country_code,
      s.location_search_text
    from public.spaces s
    where s.status = 'approved'
  )
  select
    concat_ws(', ', nullif(l.locality, ''), nullif(l.city, ''), nullif(l.state, '')) as label,
    l.locality,
    l.city,
    l.municipality,
    l.state,
    l.state_code,
    l.country_code
  from locations l
  where nullif(private.normalize_mexico_location(p_query), '') is null
     or l.location_search_text like '%' || private.normalize_mexico_location(p_query) || '%'
  order by
    (private.normalize_mexico_location(l.city) = private.normalize_mexico_location(p_query)) desc,
    l.state,
    l.city,
    l.locality nulls last
  limit least(greatest(coalesce(p_limit, 8), 1), 20);
$$;

revoke all on function public.search_mexico_locations(text, integer) from public;
grant execute on function public.search_mexico_locations(text, integer) to anon, authenticated;

comment on function public.search_mexico_locations(text, integer) is
  'Privacy-safe nationwide autocomplete sourced automatically from approved Mexico listings.';

-- ============================================================================
-- 4. SOURCE: supabase/seed.sql
-- ============================================================================

-- Development-only seed. Apply after all migrations; do not use these demo accounts in production.

insert into public.amenities (name, slug, category, icon_name) values
  ('Jacuzzi', 'jacuzzi', 'wellness', 'bath'),
  ('Pool', 'pool', 'wellness', 'waves'),
  ('Private entrance', 'private-entrance', 'privacy', 'door-open'),
  ('Private parking', 'private-parking', 'access', 'car'),
  ('Self check-in', 'self-check-in', 'privacy', 'key-round'),
  ('Soundproofing', 'soundproofing', 'privacy', 'volume-x'),
  ('Wi-Fi', 'wifi', 'comfort', 'wifi'),
  ('Air conditioning', 'air-conditioning', 'comfort', 'snowflake'),
  ('Shower', 'shower', 'wellness', 'shower-head'),
  ('Bathtub', 'bathtub', 'wellness', 'bath'),
  ('Mirrors', 'mirrors', 'studio', 'scan'),
  ('Lighting equipment', 'lighting-equipment', 'studio', 'lamp-desk'),
  ('Tripod', 'tripod', 'studio', 'camera'),
  ('Kitchen', 'kitchen', 'comfort', 'cooking-pot'),
  ('Terrace', 'terrace', 'outdoor', 'sunset'),
  ('Outdoor area', 'outdoor-area', 'outdoor', 'trees')
on conflict (slug) do update set name = excluded.name, category = excluded.category, icon_name = excluded.icon_name;

insert into public.allowed_uses (name, slug) values
  ('Intimate experiences', 'intimate_experiences'),
  ('Nudity', 'nudity'),
  ('Photography', 'photography'),
  ('Video recording', 'video_recording'),
  ('Commercial content', 'commercial_content'),
  ('Groups', 'groups'),
  ('Events', 'events'),
  ('Smoking', 'smoking'),
  ('Pets', 'pets')
on conflict (slug) do update set name = excluded.name;

-- A deterministic host and guests make review aggregation testable in local development.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
) values
  ('00000000-0000-0000-0000-000000000000', '30000000-0000-4000-8000-000000000001', 'authenticated', 'authenticated', 'host.nocturne@sinner.local', crypt('SinnerDemo2026!', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"first_name":"Nocturne","last_name":"Hospitality","display_name":"Nocturne Hospitality","date_of_birth":"1990-01-01","terms_accepted_at":"2026-01-01T00:00:00Z","privacy_accepted_at":"2026-01-01T00:00:00Z","adult_confirmation_at":"2026-01-01T00:00:00Z"}', now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', '31000000-0000-4000-8000-000000000001', 'authenticated', 'authenticated', 'guest.one@sinner.local', crypt('SinnerDemo2026!', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"first_name":"Mariana","last_name":"Demo","display_name":"Mariana","date_of_birth":"1992-04-12","terms_accepted_at":"2026-01-01T00:00:00Z","privacy_accepted_at":"2026-01-01T00:00:00Z","adult_confirmation_at":"2026-01-01T00:00:00Z"}', now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', '31000000-0000-4000-8000-000000000002', 'authenticated', 'authenticated', 'guest.two@sinner.local', crypt('SinnerDemo2026!', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"first_name":"Alex","last_name":"Demo","display_name":"Alex","date_of_birth":"1988-09-08","terms_accepted_at":"2026-01-01T00:00:00Z","privacy_accepted_at":"2026-01-01T00:00:00Z","adult_confirmation_at":"2026-01-01T00:00:00Z"}', now(), now(), '', '', '', '')
on conflict (id) do nothing;

-- Password sign-in also requires an email identity linked to each Auth user.
insert into auth.identities (
  id, user_id, provider_id, identity_data, provider,
  last_sign_in_at, created_at, updated_at
)
select
  u.id,
  u.id,
  u.id::text,
  jsonb_build_object(
    'sub', u.id::text,
    'email', u.email,
    'email_verified', true,
    'phone_verified', false
  ),
  'email',
  null,
  u.created_at,
  u.updated_at
from auth.users u
where u.id in (
  '30000000-0000-4000-8000-000000000001',
  '31000000-0000-4000-8000-000000000001',
  '31000000-0000-4000-8000-000000000002'
)
on conflict (provider_id, provider) do update set
  identity_data = excluded.identity_data,
  updated_at = excluded.updated_at;

insert into public.user_roles(user_id, role) values
  ('30000000-0000-4000-8000-000000000001', 'host')
on conflict (user_id, role) do nothing;

insert into public.spaces (
  id, host_id, name, slug, short_description, description, space_type, status,
  city, state, country, approximate_location, exact_address, max_guests,
  hourly_price, overnight_price, full_day_price, cleaning_fee, minimum_hours,
  privacy_score, instant_booking, creator_friendly, group_friendly, events_allowed,
  featured, cancellation_policy, check_in_notes, minimum_booking_notice_minutes,
  buffer_minutes, house_rules, published_at
) values
  ('00000000-0000-4000-8000-000000000001', '30000000-0000-4000-8000-000000000001', 'Midnight Loft', 'midnight-loft', 'Low light, discreet access and a private jacuzzi in central Guadalajara.', 'A low-lit private loft designed for hourly escapes, discreet content sessions and elevated after-dark experiences.', 'Private Suite', 'approved', 'Guadalajara', 'Jalisco', 'Mexico', 'Colonia Americana, Guadalajara', 'DEMO PRIVATE ADDRESS 1', 8, 350, 6800, 9200, 250, 2, 9.7, false, true, true, false, true, 'Free cancellation up to 48 hours before the selected start time.', 'Self check-in details are shared after confirmation.', 180, 45, '[{"key":"guests","label":"Maximum guests","detail":"Up to 8 registered guests"},{"key":"smoking","label":"Smoking","detail":"Not permitted indoors","allowed":false},{"key":"noise","label":"Noise","detail":"Keep sound within the private space"}]', now() - interval '2 days'),
  ('00000000-0000-4000-8000-000000000002', '30000000-0000-4000-8000-000000000001', 'The Velvet Room', 'the-velvet-room', 'A cinematic suite for two with self check-in and quiet interiors.', 'A compact private suite with a cinematic palette, self check-in and polished comfort for couples.', 'Private Suite', 'approved', 'Zapopan', 'Jalisco', 'Mexico', 'Ciudad Granja, Zapopan', 'DEMO PRIVATE ADDRESS 2', 4, 280, 4200, 6100, 200, 2, 9.4, true, false, false, false, true, 'Free cancellation up to 24 hours before arrival.', 'A private access code is released after confirmation.', 120, 30, '[{"key":"guests","label":"Maximum guests","detail":"Up to 4 registered guests"},{"key":"smoking","label":"Smoking","detail":"Not permitted","allowed":false},{"key":"events","label":"Events","detail":"Not permitted","allowed":false}]', now() - interval '4 days'),
  ('00000000-0000-4000-8000-000000000003', '30000000-0000-4000-8000-000000000001', 'Obsidian Villa', 'obsidian-villa', 'A secluded villa with pool, parking and room for curated private events.', 'A private villa for curated lifestyle events, groups and elegant nighttime gatherings.', 'Villa', 'approved', 'Guadalajara', 'Jalisco', 'Mexico', 'Las Fuentes, Guadalajara', 'DEMO PRIVATE ADDRESS 3', 20, 1200, 17500, 24000, 1200, 4, 9.9, false, true, true, true, true, 'Event cancellations require seven days notice.', 'The verified organizer meets the property manager at a nearby access point.', 1440, 120, '[{"key":"guests","label":"Maximum guests","detail":"Up to 20 registered guests"},{"key":"events","label":"Events","detail":"Approved guest lists are allowed","allowed":true},{"key":"noise","label":"Noise","detail":"Outdoor sound ends at 1 AM"}]', now() - interval '6 days'),
  ('00000000-0000-4000-8000-000000000004', '30000000-0000-4000-8000-000000000001', 'Luna Studio', 'luna-studio', 'Creator-ready studio with controlled light, mirrors and soundproofing.', 'A flexible studio for photography and video with a private changing area and configurable equipment.', 'Studio', 'approved', 'Zapopan', 'Jalisco', 'Mexico', 'Chapalita, Zapopan', 'DEMO PRIVATE ADDRESS 4', 6, 620, null, 5200, 180, 2, 9.2, true, true, true, false, false, 'Free cancellation up to 24 hours before the session.', 'Equipment requests should be sent before arrival.', 180, 30, '[{"key":"guests","label":"Maximum guests","detail":"Up to 6 registered guests"},{"key":"equipment","label":"Equipment","detail":"Return equipment to its original position"}]', now() - interval '9 days'),
  ('00000000-0000-4000-8000-000000000005', '30000000-0000-4000-8000-000000000001', 'Casa Niebla', 'casa-niebla', 'A serene apartment with a private terrace and independent entrance.', 'A quiet apartment with warm natural materials, a sheltered terrace and flexible hourly access.', 'Apartment', 'approved', 'Guadalajara', 'Jalisco', 'Mexico', 'Providencia, Guadalajara', 'DEMO PRIVATE ADDRESS 5', 4, 780, 5400, 7600, 300, 3, 9.6, false, true, false, false, false, 'Free cancellation up to 48 hours before arrival.', 'Street-level details are withheld until confirmation.', 360, 45, '[{"key":"guests","label":"Maximum guests","detail":"Up to 4 registered guests"},{"key":"events","label":"Events","detail":"Not permitted","allowed":false}]', now() - interval '12 days'),
  ('00000000-0000-4000-8000-000000000006', '30000000-0000-4000-8000-000000000001', 'Atelier Nocturne', 'atelier-nocturne', 'An industrial studio for photo, video and commercial productions.', 'An adaptable production space with tall ceilings, blackout control and a simple load-in route.', 'Studio', 'approved', 'Tlaquepaque', 'Jalisco', 'Mexico', 'Centro, Tlaquepaque', 'DEMO PRIVATE ADDRESS 6', 10, 1100, null, 8700, 350, 3, 8.9, true, true, true, false, false, 'Free cancellation up to 24 hours before the session.', 'A studio assistant provides access without entering the booked area.', 240, 45, '[{"key":"guests","label":"Maximum guests","detail":"Up to 10 registered guests"},{"key":"equipment","label":"Equipment","detail":"Production insurance may be requested"}]', now() - interval '15 days'),
  ('00000000-0000-4000-8000-000000000007', '30000000-0000-4000-8000-000000000001', 'Eclipse Playroom', 'eclipse-playroom', 'A themed private room with sound control and discreet self check-in.', 'A carefully finished themed room with durable surfaces, flexible ambient light and clear private-use rules.', 'Playroom', 'approved', 'Zapopan', 'Jalisco', 'Mexico', 'Valle Real, Zapopan', 'DEMO PRIVATE ADDRESS 7', 6, 1250, 7200, 9800, 450, 2, 9.8, false, false, true, false, false, 'Free cancellation up to 48 hours before arrival.', 'Identity verification is required before access details are released.', 360, 60, '[{"key":"guests","label":"Maximum guests","detail":"Up to 6 registered guests"},{"key":"events","label":"Events","detail":"Not permitted","allowed":false}]', now() - interval '19 days'),
  ('00000000-0000-4000-8000-000000000008', '30000000-0000-4000-8000-000000000001', 'Terraza Umbral', 'terraza-umbral', 'A discreet rooftop venue for controlled guest lists and private events.', 'An enclosed rooftop venue with covered lounge areas, service access and a host-managed entrance.', 'Venue', 'approved', 'Guadalajara', 'Jalisco', 'Mexico', 'Lafayette, Guadalajara', 'DEMO PRIVATE ADDRESS 8', 30, 2200, null, 16800, 900, 4, 8.7, false, true, true, true, false, 'Events require seven days notice for a full refund.', 'Guest-list and vendor details are reviewed before confirmation.', 2880, 120, '[{"key":"guests","label":"Maximum guests","detail":"Up to 30 registered guests"},{"key":"events","label":"Events","detail":"Approved events are allowed","allowed":true}]', now() - interval '23 days'),
  ('00000000-0000-4000-8000-000000000009', '30000000-0000-4000-8000-000000000001', 'Suite Amatista', 'suite-amatista', 'An accessible private suite with bathtub and contactless arrival.', 'A polished suite with contactless access, blackout curtains and a calm private bathroom.', 'Private Suite', 'approved', 'Tonala', 'Jalisco', 'Mexico', 'Loma Dorada, Tonala', 'DEMO PRIVATE ADDRESS 9', 2, 540, 3600, 5100, 180, 2, 9.1, true, false, false, false, false, 'Free cancellation up to 24 hours before arrival.', 'Contactless access details are shared after confirmation.', 120, 30, '[{"key":"guests","label":"Maximum guests","detail":"Up to 2 registered guests"},{"key":"smoking","label":"Smoking","detail":"Not permitted","allowed":false}]', now() - interval '28 days'),
  ('00000000-0000-4000-8000-000000000010', '30000000-0000-4000-8000-000000000001', 'Casa Cobalto', 'casa-cobalto', 'A lakeside villa with private grounds, pool and production-friendly spaces.', 'A spacious villa with enclosed gardens, a pool and varied interiors for groups and private stays.', 'Villa', 'approved', 'Ajijic', 'Jalisco', 'Mexico', 'West Ajijic, Lake Chapala', 'DEMO PRIVATE ADDRESS 10', 14, 950, 12800, 18400, 950, 4, 9.8, false, true, true, true, false, 'Free cancellation up to seven days before arrival.', 'The exact property entrance is shared only after confirmation.', 1440, 90, '[{"key":"guests","label":"Maximum guests","detail":"Up to 14 registered guests"},{"key":"pets","label":"Pets","detail":"Permitted with host approval","allowed":true}]', now() - interval '35 days'),
  ('00000000-0000-4000-8000-000000000011', '30000000-0000-4000-8000-000000000001', 'Secret Draft Suite', 'secret-draft-suite', 'A private draft used to verify that unpublished listings never leak.', 'This development-only listing must remain invisible to marketplace searches and direct public detail reads.', 'Private Suite', 'draft', 'Guadalajara', 'Jalisco', 'Mexico', 'Private draft location', 'DEMO PRIVATE DRAFT ADDRESS', 2, 500, 3400, 4800, 150, 2, 10, false, false, false, false, false, 'Draft policy.', 'Draft check-in notes.', 120, 30, '[]', null)
on conflict (id) do update set
  host_id = excluded.host_id, name = excluded.name, slug = excluded.slug,
  short_description = excluded.short_description, description = excluded.description,
  space_type = excluded.space_type, status = excluded.status, city = excluded.city,
  state = excluded.state, country = excluded.country, approximate_location = excluded.approximate_location,
  exact_address = excluded.exact_address, max_guests = excluded.max_guests,
  hourly_price = excluded.hourly_price, overnight_price = excluded.overnight_price,
  full_day_price = excluded.full_day_price, cleaning_fee = excluded.cleaning_fee,
  minimum_hours = excluded.minimum_hours, privacy_score = excluded.privacy_score,
  instant_booking = excluded.instant_booking, creator_friendly = excluded.creator_friendly,
  group_friendly = excluded.group_friendly, events_allowed = excluded.events_allowed,
  featured = excluded.featured, cancellation_policy = excluded.cancellation_policy,
  check_in_notes = excluded.check_in_notes, minimum_booking_notice_minutes = excluded.minimum_booking_notice_minutes,
  buffer_minutes = excluded.buffer_minutes, house_rules = excluded.house_rules, published_at = excluded.published_at;

-- Nationwide development markets. These values also update an already-seeded dev project.
update public.spaces as s
set
  country_code = location.country_code,
  country = location.country,
  state = location.state,
  state_code = location.state_code,
  municipality = location.municipality,
  city = location.city,
  locality = location.locality,
  postal_code = location.postal_code,
  latitude = location.latitude,
  longitude = location.longitude,
  approximate_location = location.approximate_location,
  exact_address = location.exact_address
from (values
  ('00000000-0000-4000-8000-000000000001'::uuid, 'MX', 'Mexico', 'Jalisco', 'JAL', 'Guadalajara', 'Guadalajara', 'Colonia Americana', '44160', 20.6736000, -103.3680000, 'Colonia Americana, Guadalajara, Jalisco', 'DEMO PRIVATE ADDRESS GDL'),
  ('00000000-0000-4000-8000-000000000002'::uuid, 'MX', 'Mexico', 'Ciudad de México', 'CMX', 'Cuauhtémoc', 'Ciudad de México', 'Roma Norte', '06700', 19.4180000, -99.1640000, 'Roma Norte, Ciudad de México', 'DEMO PRIVATE ADDRESS CDMX'),
  ('00000000-0000-4000-8000-000000000003'::uuid, 'MX', 'Mexico', 'Nuevo León', 'NLE', 'Monterrey', 'Monterrey', 'Obispado', '64060', 25.6780000, -100.3420000, 'Obispado, Monterrey, Nuevo León', 'DEMO PRIVATE ADDRESS MTY'),
  ('00000000-0000-4000-8000-000000000004'::uuid, 'MX', 'Mexico', 'Quintana Roo', 'ROO', 'Benito Juárez', 'Cancún', 'Zona Hotelera', '77500', 21.1210000, -86.8510000, 'Zona Hotelera, Cancún, Quintana Roo', 'DEMO PRIVATE ADDRESS CUN'),
  ('00000000-0000-4000-8000-000000000005'::uuid, 'MX', 'Mexico', 'Jalisco', 'JAL', 'Puerto Vallarta', 'Puerto Vallarta', 'Zona Romántica', '48380', 20.6530000, -105.2250000, 'Zona Romántica, Puerto Vallarta, Jalisco', 'DEMO PRIVATE ADDRESS PVR'),
  ('00000000-0000-4000-8000-000000000006'::uuid, 'MX', 'Mexico', 'Querétaro', 'QUE', 'Querétaro', 'Querétaro', 'Centro Histórico', '76000', 20.5930000, -100.3920000, 'Centro Histórico, Querétaro, Querétaro', 'DEMO PRIVATE ADDRESS QRO'),
  ('00000000-0000-4000-8000-000000000007'::uuid, 'MX', 'Mexico', 'Baja California', 'BCN', 'Tijuana', 'Tijuana', 'Zona Río', '22010', 32.5260000, -117.0200000, 'Zona Río, Tijuana, Baja California', 'DEMO PRIVATE ADDRESS TIJ'),
  ('00000000-0000-4000-8000-000000000008'::uuid, 'MX', 'Mexico', 'Yucatán', 'YUC', 'Mérida', 'Mérida', 'Centro', '97000', 20.9670000, -89.6230000, 'Centro, Mérida, Yucatán', 'DEMO PRIVATE ADDRESS MID'),
  ('00000000-0000-4000-8000-000000000009'::uuid, 'MX', 'Mexico', 'Puebla', 'PUE', 'Puebla', 'Puebla', 'Angelópolis', '72197', 19.0310000, -98.2380000, 'Angelópolis, Puebla, Puebla', 'DEMO PRIVATE ADDRESS PUE'),
  ('00000000-0000-4000-8000-000000000010'::uuid, 'MX', 'Mexico', 'Guanajuato', 'GUA', 'León', 'León', 'El Coecillo', '37260', 21.1250000, -101.6820000, 'El Coecillo, León, Guanajuato', 'DEMO PRIVATE ADDRESS BJX'),
  ('00000000-0000-4000-8000-000000000011'::uuid, 'MX', 'Mexico', 'Jalisco', 'JAL', 'Guadalajara', 'Guadalajara', 'Providencia', '44630', null, null, 'Providencia, Guadalajara, Jalisco', 'DEMO PRIVATE DRAFT ADDRESS')
) as location(
  id, country_code, country, state, state_code, municipality, city, locality,
  postal_code, latitude, longitude, approximate_location, exact_address
)
where s.id = location.id;

insert into public.space_photos (space_id, storage_path, sort_order, is_cover, alt_text) values
  ('00000000-0000-4000-8000-000000000001', 'https://images.unsplash.com/photo-1615873968403-89e068629265', 0, true, 'Midnight Loft main room'),
  ('00000000-0000-4000-8000-000000000001', 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304', 1, false, 'Midnight Loft bedroom'),
  ('00000000-0000-4000-8000-000000000001', 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b', 2, false, 'Midnight Loft lounge'),
  ('00000000-0000-4000-8000-000000000002', 'https://images.unsplash.com/photo-1590490360182-c33d57733427', 0, true, 'The Velvet Room main suite'),
  ('00000000-0000-4000-8000-000000000002', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0', 1, false, 'The Velvet Room lounge'),
  ('00000000-0000-4000-8000-000000000002', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6', 2, false, 'The Velvet Room details'),
  ('00000000-0000-4000-8000-000000000003', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c', 0, true, 'Obsidian Villa exterior'),
  ('00000000-0000-4000-8000-000000000003', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d', 1, false, 'Obsidian Villa lounge'),
  ('00000000-0000-4000-8000-000000000003', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3', 2, false, 'Obsidian Villa interior'),
  ('00000000-0000-4000-8000-000000000004', 'https://images.unsplash.com/photo-1604014237800-1c9102c219da', 0, true, 'Luna Studio'),
  ('00000000-0000-4000-8000-000000000005', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3', 0, true, 'Casa Niebla'),
  ('00000000-0000-4000-8000-000000000006', 'https://images.unsplash.com/photo-1497366811353-6870744d04b2', 0, true, 'Atelier Nocturne'),
  ('00000000-0000-4000-8000-000000000007', 'https://images.unsplash.com/photo-1617104678098-de229db51175', 0, true, 'Eclipse Playroom'),
  ('00000000-0000-4000-8000-000000000008', 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30', 0, true, 'Terraza Umbral'),
  ('00000000-0000-4000-8000-000000000009', 'https://images.unsplash.com/photo-1618773928121-c32242e63f39', 0, true, 'Suite Amatista'),
  ('00000000-0000-4000-8000-000000000010', 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde', 0, true, 'Casa Cobalto')
on conflict (space_id, storage_path) do update set sort_order = excluded.sort_order, is_cover = excluded.is_cover, alt_text = excluded.alt_text;

with assignments(space_slug, amenity_slug) as (values
  ('midnight-loft','jacuzzi'), ('midnight-loft','private-entrance'), ('midnight-loft','self-check-in'), ('midnight-loft','soundproofing'), ('midnight-loft','wifi'), ('midnight-loft','lighting-equipment'),
  ('the-velvet-room','private-entrance'), ('the-velvet-room','self-check-in'), ('the-velvet-room','soundproofing'), ('the-velvet-room','air-conditioning'), ('the-velvet-room','shower'),
  ('obsidian-villa','pool'), ('obsidian-villa','private-parking'), ('obsidian-villa','private-entrance'), ('obsidian-villa','kitchen'), ('obsidian-villa','terrace'), ('obsidian-villa','outdoor-area'),
  ('luna-studio','lighting-equipment'), ('luna-studio','tripod'), ('luna-studio','mirrors'), ('luna-studio','soundproofing'), ('luna-studio','wifi'),
  ('casa-niebla','private-entrance'), ('casa-niebla','terrace'), ('casa-niebla','bathtub'), ('casa-niebla','wifi'), ('casa-niebla','kitchen'),
  ('atelier-nocturne','lighting-equipment'), ('atelier-nocturne','tripod'), ('atelier-nocturne','mirrors'), ('atelier-nocturne','private-parking'), ('atelier-nocturne','soundproofing'),
  ('eclipse-playroom','private-entrance'), ('eclipse-playroom','self-check-in'), ('eclipse-playroom','soundproofing'), ('eclipse-playroom','jacuzzi'), ('eclipse-playroom','shower'),
  ('terraza-umbral','terrace'), ('terraza-umbral','outdoor-area'), ('terraza-umbral','private-entrance'), ('terraza-umbral','private-parking'), ('terraza-umbral','kitchen'),
  ('suite-amatista','self-check-in'), ('suite-amatista','bathtub'), ('suite-amatista','shower'), ('suite-amatista','wifi'), ('suite-amatista','private-parking'),
  ('casa-cobalto','pool'), ('casa-cobalto','outdoor-area'), ('casa-cobalto','terrace'), ('casa-cobalto','private-parking'), ('casa-cobalto','kitchen')
)
insert into public.space_amenities(space_id, amenity_id)
select s.id, a.id from assignments x join public.spaces s on s.slug = x.space_slug join public.amenities a on a.slug = x.amenity_slug
on conflict do nothing;

insert into public.space_allowed_uses (space_id, allowed_use_id, allowed)
select s.id, u.id,
  case
    when s.slug = 'midnight-loft' and u.slug = any(array['intimate_experiences','nudity','photography','video_recording','commercial_content','groups']) then true
    when s.slug = 'the-velvet-room' and u.slug = any(array['intimate_experiences','nudity','photography']) then true
    when s.slug = 'obsidian-villa' and u.slug = any(array['intimate_experiences','nudity','photography','video_recording','groups','events']) then true
    when s.slug in ('luna-studio','atelier-nocturne') and u.slug = any(array['nudity','photography','video_recording','commercial_content','groups']) then true
    when s.slug = 'casa-niebla' and u.slug = any(array['intimate_experiences','nudity','photography','video_recording']) then true
    when s.slug = 'eclipse-playroom' and u.slug = any(array['intimate_experiences','nudity','photography','groups']) then true
    when s.slug = 'terraza-umbral' and u.slug = any(array['photography','video_recording','commercial_content','groups','events']) then true
    when s.slug = 'suite-amatista' and u.slug = any(array['intimate_experiences','nudity','photography']) then true
    when s.slug = 'casa-cobalto' and u.slug = any(array['intimate_experiences','nudity','photography','video_recording','commercial_content','groups','events','pets']) then true
    else false
  end
from public.spaces s cross join public.allowed_uses u
where s.slug in ('midnight-loft','the-velvet-room','obsidian-villa','luna-studio','casa-niebla','atelier-nocturne','eclipse-playroom','terraza-umbral','suite-amatista','casa-cobalto')
on conflict (space_id, allowed_use_id) do update set allowed = excluded.allowed;

insert into public.availability(space_id, date, start_time, end_time, status) values
  ('00000000-0000-4000-8000-000000000001', current_date + 3, '20:00', '23:00', 'reserved'),
  ('00000000-0000-4000-8000-000000000001', current_date + 7, '18:00', '22:00', 'blocked'),
  ('00000000-0000-4000-8000-000000000002', current_date + 4, '21:00', '01:00', 'reserved'),
  ('00000000-0000-4000-8000-000000000003', current_date + 5, '16:00', '23:30', 'blocked')
on conflict (space_id, date, start_time, end_time) do update set status = excluded.status;

insert into public.bookings(id, guest_id, space_id, start_datetime, end_datetime, guest_count, status, base_amount, cleaning_fee, service_fee, total_amount) values
  ('40000000-0000-4000-8000-000000000001', '31000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', now() - interval '35 days', now() - interval '35 days' + interval '4 hours', 2, 'completed', 1400, 250, 182, 1832),
  ('40000000-0000-4000-8000-000000000002', '31000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', now() - interval '20 days', now() - interval '20 days' + interval '4 hours', 2, 'completed', 1400, 250, 182, 1832),
  ('40000000-0000-4000-8000-000000000003', '31000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000002', now() - interval '15 days', now() - interval '15 days' + interval '4 hours', 2, 'completed', 1120, 200, 145, 1465),
  ('40000000-0000-4000-8000-000000000004', '31000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000003', now() - interval '12 days', now() - interval '12 days' + interval '4 hours', 8, 'completed', 4800, 1200, 660, 6660)
on conflict (id) do nothing;

insert into public.reviews(id, booking_id, author_id, space_id, overall_rating, cleanliness_rating, privacy_rating, accuracy_rating, host_rating, discretion_rating, comment, created_at) values
  ('50000000-0000-4000-8000-000000000001', '40000000-0000-4000-8000-000000000001', '31000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', 5, 5, 5, 5, 5, 5, 'The arrival was discreet, the lighting was excellent and the space matched every photo.', now() - interval '30 days'),
  ('50000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000002', '31000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', 5, 5, 5, 5, 5, 5, 'Clear rules, responsive host and a genuinely private entrance.', now() - interval '15 days'),
  ('50000000-0000-4000-8000-000000000003', '40000000-0000-4000-8000-000000000003', '31000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000002', 4, 5, 5, 4, 5, 5, 'Beautiful room and very clear instructions from the host.', now() - interval '10 days'),
  ('50000000-0000-4000-8000-000000000004', '40000000-0000-4000-8000-000000000004', '31000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000003', 5, 5, 5, 5, 5, 5, 'The privacy and guest flow were exceptionally well planned for our group.', now() - interval '7 days')
on conflict (id) do nothing;

insert into public.experiences (id, host_id, name, slug, description, city, state, country, duration_minutes, max_guests, price, currency, status) values
  ('10000000-0000-4000-8000-000000000001', null, 'Private Jacuzzi Experience', 'private-jacuzzi-experience', 'Warm water, low light and complete privacy.', 'Guadalajara', 'Jalisco', 'Mexico', 180, 2, 2800, 'MXN', 'approved'),
  ('10000000-0000-4000-8000-000000000002', null, 'Couples Escape', 'couples-escape', 'A private setting designed for two.', 'Zapopan', 'Jalisco', 'Mexico', 300, 2, 3900, 'MXN', 'approved'),
  ('10000000-0000-4000-8000-000000000003', null, 'Themed Experience', 'themed-experience', 'Immersive rooms with a distinct point of view.', 'Guadalajara', 'Jalisco', 'Mexico', 240, 4, 3200, 'MXN', 'approved'),
  ('10000000-0000-4000-8000-000000000004', null, 'Private Content Studio', 'private-content-studio', 'Controlled light, discreet access and creator-ready sets.', 'Guadalajara', 'Jalisco', 'Mexico', 240, 6, 4500, 'MXN', 'approved'),
  ('10000000-0000-4000-8000-000000000005', null, 'Sensory Experience', 'sensory-experience', 'Atmosphere, sound and detail curated for the night.', 'Zapopan', 'Jalisco', 'Mexico', 180, 2, 3500, 'MXN', 'approved')
on conflict (id) do nothing;

insert into public.events (id, organizer_id, name, slug, description, city, state, country, venue_name, event_date, start_time, end_time, capacity, ticket_price, currency, visibility, status) values
  ('20000000-0000-4000-8000-000000000001', null, 'Midnight Masquerade', 'midnight-masquerade', 'A private masked social evening for verified adults.', 'Guadalajara', 'Jalisco', 'Mexico', 'Private venue', current_date + 30, '21:00', '02:00', 120, 1200, 'MXN', 'invite_only', 'approved'),
  ('20000000-0000-4000-8000-000000000002', null, 'Couples Only Night', 'couples-only-night', 'A limited private event reserved for verified couples.', 'Zapopan', 'Jalisco', 'Mexico', 'Private venue', current_date + 45, '20:00', '01:00', 80, 1600, 'MXN', 'private', 'approved'),
  ('20000000-0000-4000-8000-000000000003', null, 'After Dark Social', 'after-dark-social', 'A curated social event with discreet access and verified attendance.', 'Guadalajara', 'Jalisco', 'Mexico', 'Private venue', current_date + 60, '21:00', '02:00', 160, 900, 'MXN', 'public', 'approved')
on conflict (id) do nothing;

-- ============================================================================
-- 5. SOURCE: supabase/sql-editor/verify_phase_1_2.sql
-- ============================================================================

-- Atomic smoke checks. Any failure aborts the surrounding SQL Editor transaction.
do $sinner_verify$
declare
  expected_table text;
  expected_column text;
  expected_tables constant text[] := array[
    'profiles', 'user_roles', 'spaces', 'space_photos', 'amenities',
    'space_amenities', 'allowed_uses', 'space_allowed_uses', 'availability',
    'bookings', 'favorites', 'reviews', 'conversations',
    'conversation_participants', 'messages', 'experiences', 'events',
    'event_tickets', 'notifications', 'reports'
  ];
begin
  foreach expected_table in array expected_tables loop
    if to_regclass('public.' || expected_table) is null then
      raise exception 'SINNER verification failed: missing table public.%', expected_table;
    end if;
  end loop;

  foreach expected_column in array array[
    'country_code', 'country', 'state', 'state_code', 'municipality', 'city',
    'locality', 'postal_code', 'latitude', 'longitude', 'approximate_location',
    'exact_address', 'location_search_text'
  ] loop
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'public'
        and table_name = 'spaces'
        and column_name = expected_column
    ) then
      raise exception 'SINNER verification failed: missing spaces.%', expected_column;
    end if;
  end loop;

  if to_regclass('public.public_profiles') is null
     or to_regclass('public.public_host_profiles') is null
     or to_regclass('public.public_space_reviews') is null then
    raise exception 'SINNER verification failed: a public privacy-safe view is missing';
  end if;

  if to_regprocedure('public.check_space_availability(uuid,date,time without time zone,integer,integer)') is null then
    raise exception 'SINNER verification failed: availability RPC is missing';
  end if;

  if to_regproc('public.search_public_spaces') is null then
    raise exception 'SINNER verification failed: marketplace search RPC is missing';
  end if;

  if to_regproc('public.search_mexico_locations') is null then
    raise exception 'SINNER verification failed: Mexico autocomplete RPC is missing';
  end if;

  if private.normalize_mexico_location('queretaro')
     <> private.normalize_mexico_location('Querétaro') then
    raise exception 'SINNER verification failed: accent-insensitive location normalization is broken';
  end if;

  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = any(expected_tables)
      and c.relrowsecurity is false
  ) then
    raise exception 'SINNER verification failed: RLS is disabled on a protected table';
  end if;

  if has_column_privilege('anon', 'public.spaces', 'exact_address', 'select')
     or has_column_privilege('authenticated', 'public.spaces', 'exact_address', 'select') then
    raise exception 'SINNER verification failed: exact_address is exposed';
  end if;

  if has_column_privilege('anon', 'public.spaces', 'latitude', 'select')
     or has_column_privilege('anon', 'public.spaces', 'longitude', 'select') then
    raise exception 'SINNER verification failed: exact coordinates are exposed';
  end if;

  if has_column_privilege('anon', 'public.spaces', 'postal_code', 'select')
     or has_column_privilege('anon', 'public.spaces', 'location_search_text', 'select') then
    raise exception 'SINNER verification failed: private location fields are exposed';
  end if;

  if (select count(*) from public.spaces) <> 11
     or (select count(*) from public.spaces where status = 'approved') <> 10 then
    raise exception 'SINNER verification failed: expected 10 approved spaces and 1 draft';
  end if;

  if (select count(*) from public.amenities) < 16
     or (select count(*) from public.allowed_uses) < 9 then
    raise exception 'SINNER verification failed: marketplace taxonomy seed is incomplete';
  end if;

  if (select count(distinct state_code) from public.spaces where status = 'approved') < 9 then
    raise exception 'SINNER verification failed: nationwide development markets are incomplete';
  end if;

  if (select count(*) from auth.identities where user_id in (
    '30000000-0000-4000-8000-000000000001',
    '31000000-0000-4000-8000-000000000001',
    '31000000-0000-4000-8000-000000000002'
  )) <> 3 then
    raise exception 'SINNER verification failed: demo Auth identities are incomplete';
  end if;

  if exists (
    select 1
    from public.spaces
    where review_count <> (select count(*) from public.reviews where reviews.space_id = spaces.id)
  ) then
    raise exception 'SINNER verification failed: review aggregates are inconsistent';
  end if;

  raise notice 'SINNER Phases 1 and 2 verified successfully.';
end
$sinner_verify$;

commit;
