import type {
  PublicHost,
  PublicReview,
  SpaceAllowedUse,
  SpaceAmenity,
  SpaceDetailData,
  SpaceRule,
} from "@/lib/types/marketplace";

const amenities: Record<string, SpaceAmenity> = {
  jacuzzi: { name: "Jacuzzi", slug: "jacuzzi", category: "wellness", iconName: "bath" },
  pool: { name: "Pool", slug: "pool", category: "wellness", iconName: "waves" },
  "private-entrance": { name: "Private entrance", slug: "private-entrance", category: "privacy", iconName: "door-open" },
  "private-parking": { name: "Private parking", slug: "private-parking", category: "access", iconName: "car" },
  "self-check-in": { name: "Self check-in", slug: "self-check-in", category: "privacy", iconName: "key-round" },
  soundproofing: { name: "Soundproofing", slug: "soundproofing", category: "privacy", iconName: "volume-x" },
  wifi: { name: "Wi-Fi", slug: "wifi", category: "comfort", iconName: "wifi" },
  "air-conditioning": { name: "Air conditioning", slug: "air-conditioning", category: "comfort", iconName: "snowflake" },
  shower: { name: "Shower", slug: "shower", category: "wellness", iconName: "shower-head" },
  bathtub: { name: "Bathtub", slug: "bathtub", category: "wellness", iconName: "bath" },
  mirrors: { name: "Mirrors", slug: "mirrors", category: "studio", iconName: "scan" },
  "lighting-equipment": { name: "Lighting equipment", slug: "lighting-equipment", category: "studio", iconName: "lamp-desk" },
  tripod: { name: "Tripod", slug: "tripod", category: "studio", iconName: "camera" },
  kitchen: { name: "Kitchen", slug: "kitchen", category: "comfort", iconName: "cooking-pot" },
  terrace: { name: "Terrace", slug: "terrace", category: "outdoor", iconName: "sunset" },
  "outdoor-area": { name: "Outdoor area", slug: "outdoor-area", category: "outdoor", iconName: "trees" },
};

const allowedUseNames: Record<string, string> = {
  intimate_experiences: "Intimate experiences",
  nudity: "Nudity",
  photography: "Photography",
  video_recording: "Video recording",
  commercial_content: "Commercial content",
  groups: "Groups",
  events: "Events",
  smoking: "Smoking",
  pets: "Pets",
};

const hosts: Record<string, PublicHost> = {
  nocturne: {
    id: "30000000-0000-4000-8000-000000000001",
    displayName: "Nocturne Hospitality",
    avatarUrl: null,
    verified: true,
    memberSince: "2024-03-18T00:00:00.000Z",
    rating: 4.9,
  },
  privado: {
    id: "30000000-0000-4000-8000-000000000002",
    displayName: "Estancias Privadas GDL",
    avatarUrl: null,
    verified: true,
    memberSince: "2025-01-12T00:00:00.000Z",
    rating: 4.8,
  },
  atelier: {
    id: "30000000-0000-4000-8000-000000000003",
    displayName: "Atelier Once",
    avatarUrl: null,
    verified: false,
    memberSince: "2025-08-04T00:00:00.000Z",
    rating: 4.7,
  },
};

type FixtureInput = Omit<
  SpaceDetailData,
  "coverPhoto" | "photos" | "amenities" | "allowedUses" | "rules" | "host" | "reviews" | "ratingAverage" | "reviewCount"
> & {
  photoIds: string[];
  amenitySlugs: string[];
  allowedUseSlugs: string[];
  ruleOverrides?: SpaceRule[];
  hostKey: keyof typeof hosts;
  reviewSeeds: Array<{ rating: number; comment: string; authorName: string }>;
};

const developmentPhotoUrls = [
  "/images/hero-sinner-night.png",
  "/images/experience-couples.png",
  "/images/experience-jacuzzi.png",
  "/images/experience-studio.png",
  "/images/experience-themed.png",
  "/images/experience-sensory.png",
];

function photoUrl(id: string) {
  const index = Array.from(id).reduce((sum, character) => sum + character.charCodeAt(0), 0) % developmentPhotoUrls.length;
  return developmentPhotoUrls[index];
}

function buildFixture(input: FixtureInput): SpaceDetailData {
  const photos = input.photoIds.map((id, index) => ({
    id: `${input.id}-photo-${index + 1}`,
    url: photoUrl(id),
    sortOrder: index,
    isCover: index === 0,
    altText: `${input.name} view ${index + 1}`,
  }));
  const allowedUses: SpaceAllowedUse[] = Object.entries(allowedUseNames).map(([slug, name]) => ({
    name,
    slug,
    allowed: input.allowedUseSlugs.includes(slug),
    details: null,
  }));
  const reviews: PublicReview[] = input.reviewSeeds.map((review, index) => ({
    id: `${input.id}-review-${index + 1}`,
    rating: review.rating,
    comment: review.comment,
    authorName: review.authorName,
    authorAvatar: null,
    createdAt: new Date(Date.UTC(2026, 7 - index, 18 - index)).toISOString(),
  }));
  const ratingAverage = reviews.length
    ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length
    : 0;
  const rules: SpaceRule[] = input.ruleOverrides ?? [
    { key: "guests", label: "Maximum guests", detail: `Up to ${input.maxGuests} registered guests` },
    { key: "smoking", label: "Smoking", detail: "Not permitted indoors", allowed: false },
    { key: "noise", label: "Noise", detail: "Keep sound within the private space" },
    { key: "cleaning", label: "Cleaning", detail: "Standard cleaning is included in the estimate" },
  ];

  return {
    ...input,
    coverPhoto: photos[0]?.url ?? "/images/hero-sinner-night.png",
    photos,
    amenities: input.amenitySlugs.map((slug) => amenities[slug]).filter((item): item is SpaceAmenity => Boolean(item)),
    allowedUses,
    rules,
    host: hosts[input.hostKey],
    reviews,
    ratingAverage,
    reviewCount: reviews.length,
  };
}

export const developmentSpaces: SpaceDetailData[] = [
  buildFixture({
    id: "00000000-0000-4000-8000-000000000001",
    slug: "midnight-loft",
    name: "Midnight Loft",
    shortDescription: "Low light, discreet access and a private jacuzzi in central Guadalajara.",
    description: "A low-lit private loft designed for hourly escapes, discreet content sessions and elevated after-dark experiences. Independent access and controlled lighting keep every arrival calm and private.",
    spaceType: "Private Suite",
    city: "Guadalajara",
    state: "Jalisco",
    country: "Mexico",
    approximateLocation: "Colonia Americana, Guadalajara",
    timezone: "America/Mexico_City",
    maxGuests: 8,
    hourlyPrice: 350,
    overnightPrice: 6800,
    fullDayPrice: 9200,
    cleaningFee: 250,
    minimumHours: 2,
    privacyScore: 9.7,
    instantBooking: false,
    creatorFriendly: true,
    groupFriendly: true,
    eventsAllowed: false,
    featured: true,
    publishedAt: "2026-08-28T20:00:00.000Z",
    cancellationPolicy: "Free cancellation up to 48 hours before the selected start time.",
    checkInNotes: "Self check-in instructions are shared after a reservation is confirmed.",
    minimumBookingNoticeMinutes: 180,
    bufferMinutes: 45,
    photoIds: ["photo-1615873968403-89e068629265", "photo-1631049307264-da0ec9d70304", "photo-1582719478250-c89cae4dc85b", "photo-1578683010236-d716f9a3f461"],
    amenitySlugs: ["jacuzzi", "private-entrance", "self-check-in", "soundproofing", "wifi", "lighting-equipment"],
    allowedUseSlugs: ["intimate_experiences", "nudity", "photography", "video_recording", "commercial_content", "groups"],
    hostKey: "nocturne",
    reviewSeeds: [
      { rating: 5, authorName: "Mariana", comment: "The arrival was discreet, the lighting was excellent and the space matched every photo." },
      { rating: 5, authorName: "Alex", comment: "Clear rules, responsive host and a genuinely private entrance." },
    ],
  }),
  buildFixture({
    id: "00000000-0000-4000-8000-000000000002",
    slug: "the-velvet-room",
    name: "The Velvet Room",
    shortDescription: "A cinematic suite for two with self check-in and quiet interiors.",
    description: "A compact private suite with a cinematic palette, self check-in and polished comfort for couples. The room is set back from the street and designed for short, unhurried stays.",
    spaceType: "Private Suite",
    city: "Ciudad de México",
    state: "Ciudad de México",
    country: "Mexico",
    approximateLocation: "Roma Norte, Ciudad de México",
    timezone: "America/Mexico_City",
    maxGuests: 4,
    hourlyPrice: 280,
    overnightPrice: 4200,
    fullDayPrice: 6100,
    cleaningFee: 200,
    minimumHours: 2,
    privacyScore: 9.4,
    instantBooking: true,
    creatorFriendly: false,
    groupFriendly: false,
    eventsAllowed: false,
    featured: true,
    publishedAt: "2026-08-24T18:00:00.000Z",
    cancellationPolicy: "Free cancellation up to 24 hours before arrival.",
    checkInNotes: "A private access code is released after confirmation.",
    minimumBookingNoticeMinutes: 120,
    bufferMinutes: 30,
    photoIds: ["photo-1590490360182-c33d57733427", "photo-1600210492486-724fe5c67fb0", "photo-1618221195710-dd6b41faaea6", "photo-1600566753086-00f18fb6b3ea"],
    amenitySlugs: ["private-entrance", "self-check-in", "soundproofing", "air-conditioning", "shower"],
    allowedUseSlugs: ["intimate_experiences", "nudity", "photography"],
    hostKey: "privado",
    reviewSeeds: [
      { rating: 5, authorName: "Renata", comment: "Very quiet, spotless and easy to enter without waiting for anyone." },
      { rating: 4, authorName: "Sofia", comment: "Beautiful room and very clear instructions from the host." },
    ],
  }),
  buildFixture({
    id: "00000000-0000-4000-8000-000000000003",
    slug: "obsidian-villa",
    name: "Obsidian Villa",
    shortDescription: "A secluded villa with pool, parking and room for curated private events.",
    description: "A private villa for curated lifestyle events, groups and elegant nighttime gatherings. Its enclosed outdoor areas, controlled entrance and generous common spaces work well for planned productions and guest lists.",
    spaceType: "Villa",
    city: "Monterrey",
    state: "Nuevo León",
    country: "Mexico",
    approximateLocation: "Obispado, Monterrey, Nuevo León",
    timezone: "America/Monterrey",
    maxGuests: 20,
    hourlyPrice: 1200,
    overnightPrice: 17500,
    fullDayPrice: 24000,
    cleaningFee: 1200,
    minimumHours: 4,
    privacyScore: 9.9,
    instantBooking: false,
    creatorFriendly: true,
    groupFriendly: true,
    eventsAllowed: true,
    featured: true,
    publishedAt: "2026-08-20T19:00:00.000Z",
    cancellationPolicy: "Event cancellations require seven days notice.",
    checkInNotes: "The verified organizer meets the property manager at a nearby access point.",
    minimumBookingNoticeMinutes: 1440,
    bufferMinutes: 120,
    photoIds: ["photo-1600607687939-ce8a6c25118c", "photo-1600607687920-4e2a09cf159d", "photo-1600566753190-17f0baa2a6c3", "photo-1600607688969-a5bfcd646154"],
    amenitySlugs: ["pool", "private-parking", "private-entrance", "kitchen", "terrace", "outdoor-area"],
    allowedUseSlugs: ["intimate_experiences", "nudity", "photography", "video_recording", "groups", "events"],
    hostKey: "nocturne",
    reviewSeeds: [
      { rating: 5, authorName: "Daniel", comment: "The privacy and guest flow were exceptionally well planned for our group." },
      { rating: 5, authorName: "Andrea", comment: "A beautiful property with careful host communication and no surprises." },
    ],
  }),
  buildFixture({
    id: "00000000-0000-4000-8000-000000000004",
    slug: "luna-studio",
    name: "Luna Studio",
    shortDescription: "Creator-ready studio with controlled light, mirrors and soundproofing.",
    description: "A flexible studio for photography and video with a private changing area, clean backgrounds and equipment that can be arranged before arrival.",
    spaceType: "Studio",
    city: "Cancún",
    state: "Quintana Roo",
    country: "Mexico",
    approximateLocation: "Zona Hotelera, Cancún, Quintana Roo",
    timezone: "America/Cancun",
    maxGuests: 6,
    hourlyPrice: 620,
    overnightPrice: null,
    fullDayPrice: 5200,
    cleaningFee: 180,
    minimumHours: 2,
    privacyScore: 9.2,
    instantBooking: true,
    creatorFriendly: true,
    groupFriendly: true,
    eventsAllowed: false,
    featured: false,
    publishedAt: "2026-08-17T17:00:00.000Z",
    cancellationPolicy: "Free cancellation up to 24 hours before the session.",
    checkInNotes: "Equipment requests should be sent before arrival.",
    minimumBookingNoticeMinutes: 180,
    bufferMinutes: 30,
    photoIds: ["photo-1604014237800-1c9102c219da", "photo-1511818966892-d7d671e672a2", "photo-1600566753190-17f0baa2a6c3"],
    amenitySlugs: ["lighting-equipment", "tripod", "mirrors", "soundproofing", "wifi", "air-conditioning"],
    allowedUseSlugs: ["nudity", "photography", "video_recording", "commercial_content", "groups"],
    hostKey: "atelier",
    reviewSeeds: [{ rating: 5, authorName: "Vale", comment: "The lighting setup saved us time and the team had complete privacy." }],
  }),
  buildFixture({
    id: "00000000-0000-4000-8000-000000000005",
    slug: "casa-niebla",
    name: "Casa Niebla",
    shortDescription: "A serene apartment with a private terrace and independent entrance.",
    description: "A quiet apartment with warm natural materials, a sheltered terrace and flexible hourly access. Ideal for couples or small private productions.",
    spaceType: "Apartment",
    city: "Puerto Vallarta",
    state: "Jalisco",
    country: "Mexico",
    approximateLocation: "Zona Romántica, Puerto Vallarta, Jalisco",
    timezone: "America/Mexico_City",
    maxGuests: 4,
    hourlyPrice: 780,
    overnightPrice: 5400,
    fullDayPrice: 7600,
    cleaningFee: 300,
    minimumHours: 3,
    privacyScore: 9.6,
    instantBooking: false,
    creatorFriendly: true,
    groupFriendly: false,
    eventsAllowed: false,
    featured: false,
    publishedAt: "2026-08-13T18:00:00.000Z",
    cancellationPolicy: "Free cancellation up to 48 hours before arrival.",
    checkInNotes: "Street-level details are withheld until confirmation.",
    minimumBookingNoticeMinutes: 360,
    bufferMinutes: 45,
    photoIds: ["photo-1600566753190-17f0baa2a6c3", "photo-1600210492486-724fe5c67fb0", "photo-1618220179428-22790b461013"],
    amenitySlugs: ["private-entrance", "terrace", "bathtub", "wifi", "kitchen", "air-conditioning"],
    allowedUseSlugs: ["intimate_experiences", "nudity", "photography", "video_recording"],
    hostKey: "privado",
    reviewSeeds: [{ rating: 5, authorName: "Emilio", comment: "Quiet, refined and exactly as described. The area shown publicly was appropriately approximate." }],
  }),
  buildFixture({
    id: "00000000-0000-4000-8000-000000000006",
    slug: "atelier-nocturne",
    name: "Atelier Nocturne",
    shortDescription: "An industrial studio for photo, video and commercial productions.",
    description: "An adaptable production space with tall ceilings, blackout control and a simple load-in route for small teams and creator equipment.",
    spaceType: "Studio",
    city: "Querétaro",
    state: "Querétaro",
    country: "Mexico",
    approximateLocation: "Centro Histórico, Querétaro, Querétaro",
    timezone: "America/Mexico_City",
    maxGuests: 10,
    hourlyPrice: 1100,
    overnightPrice: null,
    fullDayPrice: 8700,
    cleaningFee: 350,
    minimumHours: 3,
    privacyScore: 8.9,
    instantBooking: true,
    creatorFriendly: true,
    groupFriendly: true,
    eventsAllowed: false,
    featured: false,
    publishedAt: "2026-08-09T16:00:00.000Z",
    cancellationPolicy: "Free cancellation up to 24 hours before the session.",
    checkInNotes: "A studio assistant provides access without entering the booked area.",
    minimumBookingNoticeMinutes: 240,
    bufferMinutes: 45,
    photoIds: ["photo-1497366811353-6870744d04b2", "photo-1497366754035-f200968a6e72", "photo-1524758631624-e2822e304c36"],
    amenitySlugs: ["lighting-equipment", "tripod", "mirrors", "private-parking", "wifi", "soundproofing"],
    allowedUseSlugs: ["nudity", "photography", "video_recording", "commercial_content", "groups"],
    hostKey: "atelier",
    reviewSeeds: [{ rating: 4, authorName: "Nico", comment: "Well equipped and straightforward. The private parking was useful for gear." }],
  }),
  buildFixture({
    id: "00000000-0000-4000-8000-000000000007",
    slug: "eclipse-playroom",
    name: "Eclipse Playroom",
    shortDescription: "A themed private room with sound control and discreet self check-in.",
    description: "A carefully finished themed room with durable surfaces, flexible ambient light and rules that clearly distinguish private use from events.",
    spaceType: "Playroom",
    city: "Tijuana",
    state: "Baja California",
    country: "Mexico",
    approximateLocation: "Zona Río, Tijuana, Baja California",
    timezone: "America/Tijuana",
    maxGuests: 6,
    hourlyPrice: 1250,
    overnightPrice: 7200,
    fullDayPrice: 9800,
    cleaningFee: 450,
    minimumHours: 2,
    privacyScore: 9.8,
    instantBooking: false,
    creatorFriendly: false,
    groupFriendly: true,
    eventsAllowed: false,
    featured: false,
    publishedAt: "2026-08-05T19:00:00.000Z",
    cancellationPolicy: "Free cancellation up to 48 hours before arrival.",
    checkInNotes: "Identity verification is required before access details are released.",
    minimumBookingNoticeMinutes: 360,
    bufferMinutes: 60,
    photoIds: ["photo-1617104678098-de229db51175", "photo-1600566753086-00f18fb6b3ea", "photo-1618221195710-dd6b41faaea6"],
    amenitySlugs: ["private-entrance", "self-check-in", "soundproofing", "jacuzzi", "shower", "air-conditioning"],
    allowedUseSlugs: ["intimate_experiences", "nudity", "photography", "groups"],
    hostKey: "nocturne",
    reviewSeeds: [{ rating: 5, authorName: "Camila", comment: "The rules were clear and the room felt genuinely private from arrival to departure." }],
  }),
  buildFixture({
    id: "00000000-0000-4000-8000-000000000008",
    slug: "terraza-umbral",
    name: "Terraza Umbral",
    shortDescription: "A discreet rooftop venue for controlled guest lists and private events.",
    description: "An enclosed rooftop venue with covered lounge areas, service access and a host-managed entrance for intimate events and small productions.",
    spaceType: "Venue",
    city: "Mérida",
    state: "Yucatán",
    country: "Mexico",
    approximateLocation: "Centro, Mérida, Yucatán",
    timezone: "America/Merida",
    maxGuests: 30,
    hourlyPrice: 2200,
    overnightPrice: null,
    fullDayPrice: 16800,
    cleaningFee: 900,
    minimumHours: 4,
    privacyScore: 8.7,
    instantBooking: false,
    creatorFriendly: true,
    groupFriendly: true,
    eventsAllowed: true,
    featured: false,
    publishedAt: "2026-07-30T20:00:00.000Z",
    cancellationPolicy: "Events require seven days notice for a full refund.",
    checkInNotes: "Guest-list and vendor details are reviewed before confirmation.",
    minimumBookingNoticeMinutes: 2880,
    bufferMinutes: 120,
    photoIds: ["photo-1492684223066-81342ee5ff30", "photo-1519167758481-83f550bb49b3", "photo-1527529482837-4698179dc6ce"],
    amenitySlugs: ["terrace", "outdoor-area", "private-entrance", "private-parking", "kitchen", "wifi"],
    allowedUseSlugs: ["photography", "video_recording", "commercial_content", "groups", "events"],
    hostKey: "privado",
    reviewSeeds: [{ rating: 4, authorName: "Luis", comment: "A well managed venue with a smooth guest-list process and plenty of privacy." }],
  }),
  buildFixture({
    id: "00000000-0000-4000-8000-000000000009",
    slug: "suite-amatista",
    name: "Suite Amatista",
    shortDescription: "An accessible private suite with bathtub and contactless arrival.",
    description: "A polished suite near the Guadalajara metropolitan area with contactless access, blackout curtains and a calm bathroom designed for private hourly stays.",
    spaceType: "Private Suite",
    city: "Puebla",
    state: "Puebla",
    country: "Mexico",
    approximateLocation: "Angelópolis, Puebla, Puebla",
    timezone: "America/Mexico_City",
    maxGuests: 2,
    hourlyPrice: 540,
    overnightPrice: 3600,
    fullDayPrice: 5100,
    cleaningFee: 180,
    minimumHours: 2,
    privacyScore: 9.1,
    instantBooking: true,
    creatorFriendly: false,
    groupFriendly: false,
    eventsAllowed: false,
    featured: false,
    publishedAt: "2026-07-24T18:00:00.000Z",
    cancellationPolicy: "Free cancellation up to 24 hours before arrival.",
    checkInNotes: "Contactless access details are shared after confirmation.",
    minimumBookingNoticeMinutes: 120,
    bufferMinutes: 30,
    photoIds: ["photo-1618773928121-c32242e63f39", "photo-1582719478250-c89cae4dc85b", "photo-1590490360182-c33d57733427"],
    amenitySlugs: ["self-check-in", "bathtub", "shower", "wifi", "air-conditioning", "private-parking"],
    allowedUseSlugs: ["intimate_experiences", "nudity", "photography"],
    hostKey: "privado",
    reviewSeeds: [{ rating: 5, authorName: "Pau", comment: "Easy arrival, very clean and quieter than expected." }],
  }),
  buildFixture({
    id: "00000000-0000-4000-8000-000000000010",
    slug: "casa-cobalto",
    name: "Casa Cobalto",
    shortDescription: "A lakeside villa with private grounds, pool and production-friendly spaces.",
    description: "A spacious villa with enclosed gardens, a pool and varied interiors for groups, day productions and private overnight stays outside the city.",
    spaceType: "Villa",
    city: "León",
    state: "Guanajuato",
    country: "Mexico",
    approximateLocation: "El Coecillo, León, Guanajuato",
    timezone: "America/Mexico_City",
    maxGuests: 14,
    hourlyPrice: 950,
    overnightPrice: 12800,
    fullDayPrice: 18400,
    cleaningFee: 950,
    minimumHours: 4,
    privacyScore: 9.8,
    instantBooking: false,
    creatorFriendly: true,
    groupFriendly: true,
    eventsAllowed: true,
    featured: false,
    publishedAt: "2026-07-18T17:00:00.000Z",
    cancellationPolicy: "Free cancellation up to seven days before arrival.",
    checkInNotes: "The exact property entrance is shared only after confirmation.",
    minimumBookingNoticeMinutes: 1440,
    bufferMinutes: 90,
    photoIds: ["photo-1600047509807-ba8f99d2cdde", "photo-1600566753190-17f0baa2a6c3", "photo-1600607687920-4e2a09cf159d"],
    amenitySlugs: ["pool", "outdoor-area", "terrace", "private-parking", "kitchen", "wifi"],
    allowedUseSlugs: ["intimate_experiences", "nudity", "photography", "video_recording", "commercial_content", "groups", "events", "pets"],
    hostKey: "nocturne",
    reviewSeeds: [{ rating: 5, authorName: "Marco", comment: "Worth the drive for the privacy. The grounds gave our group plenty of space." }],
  }),
];

export type DevelopmentAvailabilityBlock = {
  spaceId: string;
  date: string;
  start: string;
  end: string;
};

function dateWithOffset(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

export function getDevelopmentAvailabilityBlocks(): DevelopmentAvailabilityBlock[] {
  return [
    { spaceId: developmentSpaces[0].id, date: dateWithOffset(3), start: "20:00", end: "23:30" },
    { spaceId: developmentSpaces[0].id, date: dateWithOffset(7), start: "18:00", end: "22:00" },
    { spaceId: developmentSpaces[1].id, date: dateWithOffset(5), start: "21:00", end: "02:00" },
    { spaceId: developmentSpaces[2].id, date: dateWithOffset(9), start: "16:00", end: "23:59" },
  ];
}
