import type { ExperienceCategory, HostEvent, HostExperience } from "@/lib/data-access/host-content";

const input = "h-12 rounded-lg border hairline bg-black/35 px-4 text-white outline-none focus:border-sinner-gold/45";
function Field({ label, name, type="text", value, required=true, min }: { label:string; name:string; type?:string; value?:string|number; required?:boolean; min?:number }) { return <label className="grid gap-2 text-sm text-sinner-ivory"><span>{label}</span><input className={input} name={name} type={type} defaultValue={value} required={required} min={min} step={type==="number"?"any":undefined}/></label>; }
function Area({ label,name,value,required=false }: {label:string;name:string;value?:string;required?:boolean}) { return <label className="grid gap-2 text-sm text-sinner-ivory"><span>{label}</span><textarea className="min-h-28 rounded-lg border hairline bg-black/35 px-4 py-3 text-white outline-none focus:border-sinner-gold/45" name={name} defaultValue={value} required={required}/></label>; }

export function HostExperienceForm({ action, experience, categories }: { action:(data:FormData)=>void|Promise<void>; experience?:HostExperience|null; categories:ExperienceCategory[] }) {
  const firstSession=experience?.sessions[0];
  return <form action={action} className="grid gap-6"><input type="hidden" name="id" value={experience?.id??""}/>
    <section className="premium-panel grid gap-5 p-6"><h2 className="font-display text-3xl">Experience details</h2><Field label="Name" name="name" value={experience?.name}/><Field label="Short description" name="short_description" value={experience?.shortDescription}/><Area label="Full description" name="description" value={experience?.description} required/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map(c=><label key={c.id} className="flex items-center gap-3 rounded-lg border hairline p-3 text-sm text-sinner-mist"><input type="checkbox" name="categories" value={c.id} defaultChecked={experience?.categoryIds.includes(c.id)} className="accent-sinner-gold"/>{c.name}</label>)}</div></section>
    <section className="premium-panel grid gap-5 p-6"><h2 className="font-display text-3xl">Location</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="State" name="state" value={experience?.state}/><Field label="City" name="city" value={experience?.city}/><Field label="Municipality" name="municipality" value={experience?.municipality}/><Field label="Locality / neighborhood" name="locality" value={experience?.locality}/></div><Field label="Public approximate location" name="approximate_location" value={experience?.approximateLocation}/><Field label="Exact address (private until purchase)" name="exact_address" value={experience?.exactAddress}/></section>
    <section className="premium-panel p-6"><h2 className="font-display text-3xl">Format and price</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Duration (minutes)" name="duration_minutes" type="number" min={15} value={experience?.durationMinutes??60}/><Field label="Maximum guests" name="max_guests" type="number" min={1} value={experience?.maxGuests??2}/><Field label="Price MXN" name="price" type="number" min={0} value={experience?.price??0}/><Field label="Minimum age" name="minimum_age" type="number" min={18} value={experience?.minimumAge??18}/></div><div className="mt-5 grid gap-5"><Area label="What is included" name="what_is_included" value={experience?.included}/><Area label="Requirements" name="requirements" value={experience?.requirements}/><Area label="Cancellation policy" name="cancellation_policy" value={experience?.cancellationPolicy}/></div></section>
    <section className="premium-panel p-6"><h2 className="font-display text-3xl">First available session</h2><p className="mt-2 text-sm text-sinner-mist">Optional for drafts. Add the first date and more sessions can be managed after saving.</p><div className="mt-5 grid gap-4 sm:grid-cols-3"><Field label="Starts" name="session_starts_at" type="datetime-local" value={firstSession?.startsAt?.slice(0,16)} required={false}/><Field label="Ends" name="session_ends_at" type="datetime-local" value={firstSession?.endsAt?.slice(0,16)} required={false}/><Field label="Session capacity" name="session_capacity" type="number" min={1} value={firstSession?.capacity??experience?.maxGuests??2} required={false}/></div></section>
    <section className="premium-panel p-6"><h2 className="font-display text-3xl">Images</h2><input className="mt-4 block w-full rounded-lg border hairline p-3 text-sm" type="file" name="photos" multiple accept="image/jpeg,image/png,image/webp,image/gif"/></section><div className="flex gap-3"><button name="intent" value="submit" className="rounded-lg bg-sinner-gold px-5 py-3 font-semibold text-black">Submit for review</button><button name="intent" value="draft" formNoValidate className="rounded-lg border hairline px-5 py-3 text-sinner-mist">Save draft</button></div>
  </form>;
}

export function HostEventForm({ action, event }: { action:(data:FormData)=>void|Promise<void>; event?:HostEvent|null }) {
  const ticket = event?.ticketTypes[0];
  const secondTicket = event?.ticketTypes[1];
  return <form action={action} className="grid gap-6"><input type="hidden" name="id" value={event?.id??""}/>
    <section className="premium-panel grid gap-5 p-6"><h2 className="font-display text-3xl">Event details</h2><Field label="Event name" name="name" value={event?.name}/><Field label="Short description" name="short_description" value={event?.shortDescription}/><Area label="Full description" name="description" value={event?.description} required/><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Category<select name="category" defaultValue={event?.category??"other"} className={input}>{["nightlife","social","music","wellness","dining","workshop","private","other"].map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-sm">Visibility<select name="visibility" defaultValue={event?.visibility??"public"} className={input}><option value="public">Public</option><option value="private">Private</option><option value="invite_only">Invite only</option></select></label></div></section>
    <section className="premium-panel grid gap-5 p-6"><h2 className="font-display text-3xl">Venue and schedule</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Venue name" name="venue_name" value={event?.venueName}/><Field label="State" name="state" value={event?.state}/><Field label="City" name="city" value={event?.city}/><Field label="Municipality" name="municipality" value={event?.municipality}/><Field label="Locality" name="locality" value={event?.locality}/><Field label="Exact address" name="exact_address" value={event?.exactAddress}/><Field label="Date" name="event_date" type="date" value={event?.eventDate}/><Field label="Doors open" name="doors_open_time" type="time" value={event?.doorsOpenTime} required={false}/><Field label="Start" name="start_time" type="time" value={event?.startTime}/><Field label="End" name="end_time" type="time" value={event?.endTime}/><Field label="Capacity" name="capacity" type="number" min={1} value={event?.capacity??50}/><Field label="Minimum age" name="minimum_age" type="number" min={18} value={event?.minimumAge??18}/></div></section>
    <section className="premium-panel p-6"><h2 className="font-display text-3xl">Ticket types</h2><p className="mt-2 text-sm text-sinner-mist">Configure General Admission and an optional second tier such as VIP or Presale.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Primary ticket" name="ticket_name" value={ticket?.name??"General Admission"}/><Field label="Price MXN" name="ticket_price" type="number" min={0} value={ticket?.price??0}/><Field label="Quantity" name="ticket_quantity" type="number" min={1} value={ticket?.quantityTotal??event?.capacity??50}/><Field label="Maximum per order" name="max_per_order" type="number" min={1} value={ticket?.maxPerOrder??6}/></div><div className="mt-5 grid gap-4 border-t hairline pt-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Optional second ticket" name="ticket_name_2" value={secondTicket?.name} required={false}/><Field label="Second price MXN" name="ticket_price_2" type="number" min={0} value={secondTicket?.price} required={false}/><Field label="Second quantity" name="ticket_quantity_2" type="number" min={1} value={secondTicket?.quantityTotal} required={false}/><Field label="Maximum per order" name="max_per_order_2" type="number" min={1} value={secondTicket?.maxPerOrder??4} required={false}/></div><div className="mt-5 grid gap-5"><Area label="House rules" name="house_rules" value={event?.houseRules}/><Area label="Cancellation policy" name="cancellation_policy" value={event?.cancellationPolicy}/></div></section>
    <section className="premium-panel p-6"><h2 className="font-display text-3xl">Event images</h2><input className="mt-4 block w-full rounded-lg border hairline p-3 text-sm" type="file" name="photos" multiple accept="image/jpeg,image/png,image/webp,image/gif"/></section><div className="flex gap-3"><button name="intent" value="submit" className="rounded-lg bg-sinner-gold px-5 py-3 font-semibold text-black">Submit for review</button><button name="intent" value="draft" formNoValidate className="rounded-lg border hairline px-5 py-3 text-sinner-mist">Save draft</button></div>
  </form>;
}
