export type LocationSuggestion = {
  label: string;
  locality: string | null;
  city: string;
  municipality: string | null;
  state: string;
  stateCode: string;
  countryCode: "MX";
};

export interface LocationAutocompleteProvider {
  search(query: string, limit: number): Promise<LocationSuggestion[]>;
}

export function normalizeMexicoLocation(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

const locations: Array<Omit<LocationSuggestion, "locality" | "municipality" | "countryCode">> = [
  { label: "Aguascalientes, Aguascalientes", city: "Aguascalientes", state: "Aguascalientes", stateCode: "AGU" },
  { label: "Mexicali, Baja California", city: "Mexicali", state: "Baja California", stateCode: "BCN" },
  { label: "Tijuana, Baja California", city: "Tijuana", state: "Baja California", stateCode: "BCN" },
  { label: "La Paz, Baja California Sur", city: "La Paz", state: "Baja California Sur", stateCode: "BCS" },
  { label: "Campeche, Campeche", city: "Campeche", state: "Campeche", stateCode: "CAM" },
  { label: "Tuxtla Gutiérrez, Chiapas", city: "Tuxtla Gutiérrez", state: "Chiapas", stateCode: "CHP" },
  { label: "Chihuahua, Chihuahua", city: "Chihuahua", state: "Chihuahua", stateCode: "CHH" },
  { label: "Ciudad de México", city: "Ciudad de México", state: "Ciudad de México", stateCode: "CMX" },
  { label: "Saltillo, Coahuila", city: "Saltillo", state: "Coahuila de Zaragoza", stateCode: "COA" },
  { label: "Colima, Colima", city: "Colima", state: "Colima", stateCode: "COL" },
  { label: "Durango, Durango", city: "Durango", state: "Durango", stateCode: "DUR" },
  { label: "Toluca, Estado de México", city: "Toluca", state: "México", stateCode: "MEX" },
  { label: "León, Guanajuato", city: "León", state: "Guanajuato", stateCode: "GUA" },
  { label: "Acapulco, Guerrero", city: "Acapulco", state: "Guerrero", stateCode: "GRO" },
  { label: "Pachuca, Hidalgo", city: "Pachuca", state: "Hidalgo", stateCode: "HID" },
  { label: "Guadalajara, Jalisco", city: "Guadalajara", state: "Jalisco", stateCode: "JAL" },
  { label: "Puerto Vallarta, Jalisco", city: "Puerto Vallarta", state: "Jalisco", stateCode: "JAL" },
  { label: "Zapopan, Jalisco", city: "Zapopan", state: "Jalisco", stateCode: "JAL" },
  { label: "Morelia, Michoacán", city: "Morelia", state: "Michoacán de Ocampo", stateCode: "MIC" },
  { label: "Cuernavaca, Morelos", city: "Cuernavaca", state: "Morelos", stateCode: "MOR" },
  { label: "Tepic, Nayarit", city: "Tepic", state: "Nayarit", stateCode: "NAY" },
  { label: "Monterrey, Nuevo León", city: "Monterrey", state: "Nuevo León", stateCode: "NLE" },
  { label: "Oaxaca, Oaxaca", city: "Oaxaca de Juárez", state: "Oaxaca", stateCode: "OAX" },
  { label: "Puebla, Puebla", city: "Puebla", state: "Puebla", stateCode: "PUE" },
  { label: "Querétaro, Querétaro", city: "Querétaro", state: "Querétaro", stateCode: "QUE" },
  { label: "Cancún, Quintana Roo", city: "Cancún", state: "Quintana Roo", stateCode: "ROO" },
  { label: "Playa del Carmen, Quintana Roo", city: "Playa del Carmen", state: "Quintana Roo", stateCode: "ROO" },
  { label: "San Luis Potosí, San Luis Potosí", city: "San Luis Potosí", state: "San Luis Potosí", stateCode: "SLP" },
  { label: "Culiacán, Sinaloa", city: "Culiacán", state: "Sinaloa", stateCode: "SIN" },
  { label: "Hermosillo, Sonora", city: "Hermosillo", state: "Sonora", stateCode: "SON" },
  { label: "Villahermosa, Tabasco", city: "Villahermosa", state: "Tabasco", stateCode: "TAB" },
  { label: "Tampico, Tamaulipas", city: "Tampico", state: "Tamaulipas", stateCode: "TAM" },
  { label: "Tlaxcala, Tlaxcala", city: "Tlaxcala", state: "Tlaxcala", stateCode: "TLA" },
  { label: "Veracruz, Veracruz", city: "Veracruz", state: "Veracruz de Ignacio de la Llave", stateCode: "VER" },
  { label: "Mérida, Yucatán", city: "Mérida", state: "Yucatán", stateCode: "YUC" },
  { label: "Zacatecas, Zacatecas", city: "Zacatecas", state: "Zacatecas", stateCode: "ZAC" },
  { label: "Jesús María, Aguascalientes", city: "Jesús María", state: "Aguascalientes", stateCode: "AGU" },
  { label: "Ensenada, Baja California", city: "Ensenada", state: "Baja California", stateCode: "BCN" },
  { label: "Rosarito, Baja California", city: "Playas de Rosarito", state: "Baja California", stateCode: "BCN" },
  { label: "Tecate, Baja California", city: "Tecate", state: "Baja California", stateCode: "BCN" },
  { label: "Los Cabos, Baja California Sur", city: "Los Cabos", state: "Baja California Sur", stateCode: "BCS" },
  { label: "San José del Cabo, Baja California Sur", city: "San José del Cabo", state: "Baja California Sur", stateCode: "BCS" },
  { label: "Cabo San Lucas, Baja California Sur", city: "Cabo San Lucas", state: "Baja California Sur", stateCode: "BCS" },
  { label: "Ciudad del Carmen, Campeche", city: "Ciudad del Carmen", state: "Campeche", stateCode: "CAM" },
  { label: "San Cristóbal de las Casas, Chiapas", city: "San Cristóbal de las Casas", state: "Chiapas", stateCode: "CHP" },
  { label: "Tapachula, Chiapas", city: "Tapachula", state: "Chiapas", stateCode: "CHP" },
  { label: "Ciudad Juárez, Chihuahua", city: "Ciudad Juárez", state: "Chihuahua", stateCode: "CHH" },
  { label: "Delicias, Chihuahua", city: "Delicias", state: "Chihuahua", stateCode: "CHH" },
  { label: "Cuauhtémoc, Chihuahua", city: "Cuauhtémoc", state: "Chihuahua", stateCode: "CHH" },
  { label: "Álvaro Obregón, Ciudad de México", city: "Álvaro Obregón", state: "Ciudad de México", stateCode: "CMX" },
  { label: "Benito Juárez, Ciudad de México", city: "Benito Juárez", state: "Ciudad de México", stateCode: "CMX" },
  { label: "Coyoacán, Ciudad de México", city: "Coyoacán", state: "Ciudad de México", stateCode: "CMX" },
  { label: "Cuauhtémoc, Ciudad de México", city: "Cuauhtémoc", state: "Ciudad de México", stateCode: "CMX" },
  { label: "Miguel Hidalgo, Ciudad de México", city: "Miguel Hidalgo", state: "Ciudad de México", stateCode: "CMX" },
  { label: "Roma Norte, Ciudad de México", city: "Roma Norte", state: "Ciudad de México", stateCode: "CMX" },
  { label: "Condesa, Ciudad de México", city: "Condesa", state: "Ciudad de México", stateCode: "CMX" },
  { label: "Polanco, Ciudad de México", city: "Polanco", state: "Ciudad de México", stateCode: "CMX" },
  { label: "Torreón, Coahuila", city: "Torreón", state: "Coahuila de Zaragoza", stateCode: "COA" },
  { label: "Monclova, Coahuila", city: "Monclova", state: "Coahuila de Zaragoza", stateCode: "COA" },
  { label: "Manzanillo, Colima", city: "Manzanillo", state: "Colima", stateCode: "COL" },
  { label: "Gómez Palacio, Durango", city: "Gómez Palacio", state: "Durango", stateCode: "DUR" },
  { label: "Metepec, Estado de México", city: "Metepec", state: "México", stateCode: "MEX" },
  { label: "Naucalpan, Estado de México", city: "Naucalpan de Juárez", state: "México", stateCode: "MEX" },
  { label: "Tlalnepantla, Estado de México", city: "Tlalnepantla de Baz", state: "México", stateCode: "MEX" },
  { label: "Atizapán de Zaragoza, Estado de México", city: "Atizapán de Zaragoza", state: "México", stateCode: "MEX" },
  { label: "Huixquilucan, Estado de México", city: "Huixquilucan", state: "México", stateCode: "MEX" },
  { label: "Interlomas, Estado de México", city: "Interlomas", state: "México", stateCode: "MEX" },
  { label: "Ecatepec, Estado de México", city: "Ecatepec de Morelos", state: "México", stateCode: "MEX" },
  { label: "Nezahualcóyotl, Estado de México", city: "Nezahualcóyotl", state: "México", stateCode: "MEX" },
  { label: "Irapuato, Guanajuato", city: "Irapuato", state: "Guanajuato", stateCode: "GUA" },
  { label: "Celaya, Guanajuato", city: "Celaya", state: "Guanajuato", stateCode: "GUA" },
  { label: "Guanajuato, Guanajuato", city: "Guanajuato", state: "Guanajuato", stateCode: "GUA" },
  { label: "San Miguel de Allende, Guanajuato", city: "San Miguel de Allende", state: "Guanajuato", stateCode: "GUA" },
  { label: "Zihuatanejo, Guerrero", city: "Zihuatanejo", state: "Guerrero", stateCode: "GRO" },
  { label: "Ixtapa, Guerrero", city: "Ixtapa", state: "Guerrero", stateCode: "GRO" },
  { label: "Tulancingo, Hidalgo", city: "Tulancingo", state: "Hidalgo", stateCode: "HID" },
  { label: "Tlaquepaque, Jalisco", city: "San Pedro Tlaquepaque", state: "Jalisco", stateCode: "JAL" },
  { label: "Tonalá, Jalisco", city: "Tonalá", state: "Jalisco", stateCode: "JAL" },
  { label: "Tlajomulco, Jalisco", city: "Tlajomulco de Zúñiga", state: "Jalisco", stateCode: "JAL" },
  { label: "Chapala, Jalisco", city: "Chapala", state: "Jalisco", stateCode: "JAL" },
  { label: "Ajijic, Jalisco", city: "Ajijic", state: "Jalisco", stateCode: "JAL" },
  { label: "Ciudad Guzmán, Jalisco", city: "Ciudad Guzmán", state: "Jalisco", stateCode: "JAL" },
  { label: "Uruapan, Michoacán", city: "Uruapan", state: "Michoacán de Ocampo", stateCode: "MIC" },
  { label: "Pátzcuaro, Michoacán", city: "Pátzcuaro", state: "Michoacán de Ocampo", stateCode: "MIC" },
  { label: "Jiutepec, Morelos", city: "Jiutepec", state: "Morelos", stateCode: "MOR" },
  { label: "Cuautla, Morelos", city: "Cuautla", state: "Morelos", stateCode: "MOR" },
  { label: "Nuevo Vallarta, Nayarit", city: "Nuevo Vallarta", state: "Nayarit", stateCode: "NAY" },
  { label: "Bahía de Banderas, Nayarit", city: "Bahía de Banderas", state: "Nayarit", stateCode: "NAY" },
  { label: "San Pedro Garza García, Nuevo León", city: "San Pedro Garza García", state: "Nuevo León", stateCode: "NLE" },
  { label: "San Nicolás de los Garza, Nuevo León", city: "San Nicolás de los Garza", state: "Nuevo León", stateCode: "NLE" },
  { label: "Guadalupe, Nuevo León", city: "Guadalupe", state: "Nuevo León", stateCode: "NLE" },
  { label: "Apodaca, Nuevo León", city: "Apodaca", state: "Nuevo León", stateCode: "NLE" },
  { label: "Santa Catarina, Nuevo León", city: "Santa Catarina", state: "Nuevo León", stateCode: "NLE" },
  { label: "Santiago, Nuevo León", city: "Santiago", state: "Nuevo León", stateCode: "NLE" },
  { label: "Puerto Escondido, Oaxaca", city: "Puerto Escondido", state: "Oaxaca", stateCode: "OAX" },
  { label: "Huatulco, Oaxaca", city: "Santa María Huatulco", state: "Oaxaca", stateCode: "OAX" },
  { label: "Cholula, Puebla", city: "San Andrés Cholula", state: "Puebla", stateCode: "PUE" },
  { label: "San Pedro Cholula, Puebla", city: "San Pedro Cholula", state: "Puebla", stateCode: "PUE" },
  { label: "Tehuacán, Puebla", city: "Tehuacán", state: "Puebla", stateCode: "PUE" },
  { label: "San Juan del Río, Querétaro", city: "San Juan del Río", state: "Querétaro", stateCode: "QUE" },
  { label: "Corregidora, Querétaro", city: "Corregidora", state: "Querétaro", stateCode: "QUE" },
  { label: "El Marqués, Querétaro", city: "El Marqués", state: "Querétaro", stateCode: "QUE" },
  { label: "Tulum, Quintana Roo", city: "Tulum", state: "Quintana Roo", stateCode: "ROO" },
  { label: "Cozumel, Quintana Roo", city: "Cozumel", state: "Quintana Roo", stateCode: "ROO" },
  { label: "Isla Mujeres, Quintana Roo", city: "Isla Mujeres", state: "Quintana Roo", stateCode: "ROO" },
  { label: "Chetumal, Quintana Roo", city: "Chetumal", state: "Quintana Roo", stateCode: "ROO" },
  { label: "Soledad de Graciano Sánchez, San Luis Potosí", city: "Soledad de Graciano Sánchez", state: "San Luis Potosí", stateCode: "SLP" },
  { label: "Mazatlán, Sinaloa", city: "Mazatlán", state: "Sinaloa", stateCode: "SIN" },
  { label: "Los Mochis, Sinaloa", city: "Los Mochis", state: "Sinaloa", stateCode: "SIN" },
  { label: "Ciudad Obregón, Sonora", city: "Ciudad Obregón", state: "Sonora", stateCode: "SON" },
  { label: "Nogales, Sonora", city: "Nogales", state: "Sonora", stateCode: "SON" },
  { label: "Navojoa, Sonora", city: "Navojoa", state: "Sonora", stateCode: "SON" },
  { label: "Comalcalco, Tabasco", city: "Comalcalco", state: "Tabasco", stateCode: "TAB" },
  { label: "Ciudad Victoria, Tamaulipas", city: "Ciudad Victoria", state: "Tamaulipas", stateCode: "TAM" },
  { label: "Reynosa, Tamaulipas", city: "Reynosa", state: "Tamaulipas", stateCode: "TAM" },
  { label: "Matamoros, Tamaulipas", city: "Matamoros", state: "Tamaulipas", stateCode: "TAM" },
  { label: "Nuevo Laredo, Tamaulipas", city: "Nuevo Laredo", state: "Tamaulipas", stateCode: "TAM" },
  { label: "Apizaco, Tlaxcala", city: "Apizaco", state: "Tlaxcala", stateCode: "TLA" },
  { label: "Xalapa, Veracruz", city: "Xalapa", state: "Veracruz de Ignacio de la Llave", stateCode: "VER" },
  { label: "Boca del Río, Veracruz", city: "Boca del Río", state: "Veracruz de Ignacio de la Llave", stateCode: "VER" },
  { label: "Coatzacoalcos, Veracruz", city: "Coatzacoalcos", state: "Veracruz de Ignacio de la Llave", stateCode: "VER" },
  { label: "Orizaba, Veracruz", city: "Orizaba", state: "Veracruz de Ignacio de la Llave", stateCode: "VER" },
  { label: "Córdoba, Veracruz", city: "Córdoba", state: "Veracruz de Ignacio de la Llave", stateCode: "VER" },
  { label: "Progreso, Yucatán", city: "Progreso", state: "Yucatán", stateCode: "YUC" },
  { label: "Valladolid, Yucatán", city: "Valladolid", state: "Yucatán", stateCode: "YUC" },
  { label: "Guadalupe, Zacatecas", city: "Guadalupe", state: "Zacatecas", stateCode: "ZAC" },
];

export const mexicoLocationDataset: LocationSuggestion[] = locations.map((location) => ({
  ...location,
  locality: null,
  municipality: null,
  countryCode: "MX",
}));
